### ISSUE TITLE
error storing credentials - err: exit status 1, out: `not implemented`

### ISSUE THREAD

**Issue by shumkov** [awslabs/amazon-ecr-credential-helper#102]
Hi there,

I got the strange error:

```bash
~/build/dashevo/dashdrive$ eval $(aws ecr get-login --no-include-email)
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`

~/build/dashevo/dashdrive$ cat ~/.docker/config.json
{
    "credsStore":"ecr-login"
}

~/build/dashevo/dashdrive$ docker-credential-ecr-login version
0.6.0

~/build/dashevo/dashdrive$ docker version
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:21:14 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:19:24 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

Credentials exported as env vars:
```
Setting environment variables from repository settings
$ export AWS_SECRET_ACCESS_KEY=[secure]
$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_DEFAULT_REGION=[secure]
```

**Comment by shumkov** [comment]
Ops... Sorry, I should not use `eval $(aws ecr get-login --no-include-email)` anymore.

**Comment by apremalal** [comment]
@shumkov what did you use to solve this issue?

**Comment by bondxf** [comment]
@shumkov I also experienced the same issue. Could you share what you did to solve the issue?

**Comment by shumkov** [comment]
@apremalal @bondxf 
1. Configure docker daemon:
```
{
    "credsStore":"ecr-login"
}
```
2. Export your AWS credentials to env:
```
export AWS_SECRET_ACCESS_KEY=[secure]
export AWS_ACCESS_KEY_ID=[secure]
export AWS_DEFAULT_REGION=[secure]
```

Then you can pull/push your image without `docker login`.

**Comment by marcomagdy** [comment]
This is how you solve the issue actually. https://github.com/aws/aws-cli/issues/3264#issuecomment-381478869

**Comment by Nuru** [comment]
There is no need to use `docker login` or `docker logout` when using the ecr-credential-helper. You are authenticated automatically when needed by `docker`.

**Comment by ttyz** [comment]
While I agree that there is no need to call `docker login` with the credential helper, the problem still remains, some tools do call it (cdk will call `docker login` when using `Image.fromAsset()` as an example). So it think there should be a fallback that stores the credentials, and not a `not implemented` error

**Comment by PrimeTimeTran** [comment]
I turned docker on and it fixed this error for me.
https://stackoverflow.com/questions/72645895/credential-saving-error-when-connecting-to-service-on-docker

**Comment by gmmvllfrt** [comment]
I also encountered this, 
`Error saving credentials: error storing credentials - err: exit status 1, out: not implemented `

Solution that works on my end, I run: `nano ~/.docker/config.json`
then from `"credsStore" : "ecr-login"` I change the value of credsStore to `"credsStore" : "osxkeychain"`
after that I run the login aws command again and **Login Succeeded**

**Comment by gnumoksha** [comment]
I'm running Gnu/Linux and the following worked for me:
- remove the entire `credHelpers` and the comma from `~/.config/docker/config.json`
- aws ecr get-login-password | docker login --username AWS --password-stdin MY_ECR_ID.dkr.ecr.us-east-1.amazonaws.com

**Comment by sterling000** [comment]
Why was this closed, literally the entire point of this project is so you don't have to call docker login, and then it breaks any other repositories, if you have some images being pulled from docker hub and some being pulled from aws ecr, all the docker hub entries are broken and the comments in here say to remove the credHelpers and go back to using docker login command.

**Comment by bcouetil** [comment]
I just experienced that as well, in CI. What is strange is that it works a few weeks ago... within same Docker image 20.10...

I need to pull image from ECR and push to OVH.

What I ended up doing, is removing `~/.docker/config.json` after pulling the ECR image, to be able to authenticate to OVH registry and pushing the image.

**Comment by jonathanmdr** [comment]
This worked for me!

**Error:** `Error saving credentials: error storing credentials - err: exit status 1, out: not implemented`
**Solution:** I edited the file `~/.docker/config.json` changing from `"credsStore" : "ecr-login"` to `"credsStore" : "osxkeychain"`.

**Comment by pauldthomson** [comment]
> This worked for me!
> 
> **Error:** `Error saving credentials: error storing credentials - err: exit status 1, out: not implemented` **Solution:** I edited the file `~/.docker/config.json` changing from `"credsStore": "ecr-login"` to `"credsStore": "osxkeychain"`.

I don't think this is the right solution. It looks like `docker login` calls the `store` command for any configured credential helper, which calls the `Add` function in the helper interface, and this one hasn't implemented it: https://github.com/awslabs/amazon-ecr-credential-helper/blob/5c087f35e29c21d4e42a4c999c7e6c4cad32d7db/ecr-login/ecr.go#L75. I think it "works" since on a pull the `Get` function is called, and this helper checks its cache for an existing valid token before generating a new one and storing it (which is what the `Add` would have done). 

Changing the configured cred helper means not using this credential helper at all.

**Comment by ju2wheels** [comment]
> @apremalal @bondxf
> 
> 1. Configure docker daemon:
> 
> ```
> {
>     "credsStore":"ecr-login"
> }
> ```
> 
> 2. Export your AWS credentials to env:
> 
> ```
> export AWS_SECRET_ACCESS_KEY=[secure]
> export AWS_ACCESS_KEY_ID=[secure]
> export AWS_DEFAULT_REGION=[secure]
> ```
> 
> Then you can pull/push your images without `docker login`.

Why does it need the default region if that can be inferred from the repo URI? Is this issue even fixed, I see the ticket was closed but no PRs referencing it. Its still unclear if its expected that you cannot use `docker login` for Docker Hub alongside this plugin or not.

**Comment by rulatir** [comment]
> @apremalal @bondxf
> 
> 1. Configure docker daemon:
> 
> ```
> {
>     "credsStore":"ecr-login"
> }
> ```

Nonsense. This changes (or forces a particular value of) a Global Setting For Everything just to solve One Problem With One Thing.

**Comment by dnwls16071** [comment]
I changed it like this!

> Configure docker daemon:

```json
{
	"credsStore": ""
}
```

Then I was able to resolve it by searching for authentication tokens among AWS ECR's push commands and running the CLI to authenticate the Docker client against the registry!

**Comment by pauldthomson** [comment]
> I changed it like this!
> 
> > Configure docker daemon:
> 
> ```json
> {
> 	"credsStore": ""
> }
> ```
> 
> Then I was able to resolve it by searching for authentication tokens among AWS ECR's push commands and running the CLI to authenticate the Docker client against the registry!

Again I think you're just _not_ using the cred helper now 🤷‍♂️

**Comment by dnwls16071** [comment]
> > I changed it like this!
> > > Configure docker daemon:
> > 
> > 
> > {
> > 	"credsStore": ""
> > }
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I was able to resolve it by searching for authentication tokens among AWS ECR's push commands and running the CLI to authenticate the Docker client against the registry!
> 
> Again I think you're just _not_ using the cred helper now 🤷‍♂️

You might think so...

Credentials exported as env vars:

Setting environment variables from repository settings
$ export AWS_SECRET_ACCESS_KEY=[secure]
$ export AWS_ACCESS_KEY_ID=[secure]
$ export AWS_DEFAULT_REGION=[secure]

After setting it as above, the AWS ECR pushes the command, and when the information is viewed again after the distribution operates normally, the authentication information is stored well
