### ISSUE TITLE
ECR in gitlab-ci 

### ISSUE THREAD

**Issue by ghost** [awslabs/amazon-ecr-credential-helper#104]
I am trying to implement ecr in gitlab+runner+autoscaling which uses a docker+machine, I was wondering if anyone was able to implement it. 
My  main aim , is to pull ecr image directly without using docker:latest image. 

However if i use the ecr image i am getting an error ERROR: Preparation failed: Error response from daemon: Get https://xxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/dev/sbt/manifests/latest: no basic auth credentials

I am have installed the ecr using make on the Vm that the docker-machine has created , The AMI the docker-machine uses has built in docker ecr installed. i am able to pull ecr images in that vm, but fails if i try to run it via build in gitlab-ci.  

It may / may not be correct place to post this question also just trying to get some help!

Thanks

**Comment by ntman4real** [comment]
@ghost 
Did you put your aws creds in the CI/CD settings under 'secret variables'?

**Comment by lavinia09** [comment]
I am having the same problem. I did add the aws credentials in the CI/CD settings. Anybody has a solution for this?

**Comment by gumieri** [comment]
Use the [CI variable](https://docs.gitlab.com/ce/ci/variables/README.html#variables):
```
DOCKER_AUTH_CONFIG='{ "credsStore": "ecr-login" }'
```
or
```
DOCKER_AUTH_CONFIG='{"credHelpers": {"aws_account_id.dkr.ecr.region.amazonaws.com": "ecr-login"}}'
```

source:
https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#define-an-image-from-a-private-container-registry

**Comment by josephspurrier** [comment]
I had to remove the vendor directory and grab the latest packages for it to work for me: https://gitlab.com/gitlab-org/gitlab-runner/issues/1583#note_112588198

**Comment by samuelkarp** [comment]
@josephspurrier Can you try https://github.com/awslabs/amazon-ecr-credential-helper/pull/120?  I've updated the vendored dependencies in that PR.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@ghost I also wanted to pull the ECR docker image directly and build a new gitlab-runner-with-ecr docker image. check out below

https://github.com/aluc-io/gitlab-runner-with-ecr
or
https://hub.docker.com/r/alucio/gitlab-runner-with-ecr/

**Comment by burdandrei** [comment]
https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/1386 this adds the ability to use ecr creds helper as helper

**Comment by samuelkarp** [comment]
It sounds like GitLab has added support for credential helpers.  There are now binary releases of the credential helper available for download (see [v0.3.1](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1)).  I'm closing this issue for now, but please feel free to open a new issue if you continue to have difficulty using the credential helper.  If anyone wants to write documentation for setting up the credential helper with GitLab, we would be able to take that as a contribution.

**Comment by chandrangreat** [comment]
I tried using the credential helper. I am unable to do it if I have two separate accounts in .docker/config.json or in DOCKER_AUTH_CONFIG variable  like below:

```
{
  "credHelpers": {
           "aws_account_id_1.dkr.ecr.region.amazonaws.com": "ecr-login",
           ""aws_account_id_2.dkr.ecr.region.amazonaws.com": "ecr-login""
       }
}
```
In https://github.com/awslabs/amazon-ecr-credential-helper they said you can set AWS_PROFILE environment variable to the profile of AWS account. Still unable to pull the image. Any ideas on this

**Comment by celowsky** [comment]
@samuelkarp I would be amenable to getting some documentation on setting up the credential helper with Gitlab. I've been struggling with it the past day or two.
