### ISSUE TITLE
Can not pull via docker-compose

### ISSUE THREAD

**Issue by tuannvm** [awslabs/amazon-ecr-credential-helper#11]
As the title, pulling image by using `docker-compose pull` doesn't work, `ERROR: unauthorized: authentication required`
 pushing is fine.

**Comment by samuelkarp** [comment]
@tuannvm Thanks for reporting.  It looks like docker-compose doesn't work with the credential helpers yet: https://github.com/docker/compose/issues/3683

> Isnt that related to the credential helper? docker-compose, even if found the configuration, will refuse to auth if the credentials are not stored in the config.json but rather in the keychain

**Comment by samuelkarp** [comment]
It looks like Docker Compose now supports credential helpers with version 1.10.0; see https://github.com/docker/compose/issues/3683#issuecomment-276807977.  If you're still experiencing problems, let us know.
