### ISSUE TITLE
How to use golang library with assumerole

### ISSUE THREAD

**Issue by hibbert** [awslabs/amazon-ecr-credential-helper#112]
Hi,

I'm looking to use the ECR in golang, prior to running the ECR helper I'm looking to assume a role. This will provide me with some creds but I am unsure where to put this into the call to ECRHelper.

Thanks

**Comment by samuelkarp** [comment]
Hi, apologies for the delayed response.  You can configure the credential helper to use your custom AWS credential provider prior to calling either [`api.NewClient`](https://github.com/awslabs/amazon-ecr-credential-helper/blob/v0.2.0/ecr-login/api/factory.go#L35) or [`api.NewClientWithOptions`](https://github.com/awslabs/amazon-ecr-credential-helper/blob/v0.2.0/ecr-login/api/factory.go#L36).
