### ISSUE TITLE
no basic auth credentials error in docker container on ec2 instance

### ISSUE THREAD

**Issue by grezar** [awslabs/amazon-ecr-credential-helper#113]
Hi there.
I'm using amazon-ecr-credential-helper in docker container on ec2 instance. [AmazonEC2ContainerServiceforEC2Role](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/instance_IAM_role.html) is attached to that ec2 as iam role.

I build amazon-ecr-credential-helper by entrypoint.sh when container start-up like below.
```
if [[ -e /var/run/docker.sock ]]; then
  git clone https://github.com/awslabs/amazon-ecr-credential-helper.git /tmp/ecs/amazon-ecr-credential-helper
  cd /tmp/ecs/amazon-ecr-credential-helper
  make docker
  mv bin/local/docker-credential-ecr-login /usr/local/bin
  chmod +x /usr/local/bin/docker-credential-ecr-login
  cd /
  rm -rf /tmp/ecs
fi
```
I mount `/tmp` and `docker.sock` on container.
I need to mount docker.sock because of other reasons(but omit it here).
amazon-ecr-credential-helper generates binary  under `/tmp/ecs/amazon-ecr-credential-helper/bin/local` on host(and it's shared with a container).
This is a build log.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/27184133/41285632-c4a500fc-6e77-11e8-9141-27c259879774.png">

Then I executed docker pull <image that pushed to ecr> in docker container, It failed with `no basic auth credentials` error.

**Comment by deyangyin** [comment]
Hello @grezar , are you trying to use creds helper in your docker container? If so, please make sure that your AWS Credentials are stored in your container.

> You also must have AWS credentials available in one of the standard locations:
The ~/.aws/credentials file
The AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
An IAM role for Amazon EC2
If you are working with an assumed role please set the environment variable: AWS_SDK_LOAD_CONFIG=true also.

**Comment by spazm** [comment]
@grezar : did you figure out what was wrong?  

I ran into a similar problem with docker pull giving a `no basic auth credentials` error.   After all sorts of my poking and prodding,  none of which seemed to do anything, it started working.  Wondering if it was a cached bad credential?

There are some logs and a cache file in `~/.ecr/`.  May be useful to the next person who runs into a problem.
