### ISSUE TITLE
Allow user-defined AWS_PROFILE and AWS_REGION

### ISSUE THREAD

**Issue by yuelipku** [awslabs/amazon-ecr-credential-helper#114]
hi,
I am wondering if it is possible to add a configure file in this pacakge, where user can define their own AWS_PROFILE and AWS_REGION.
I have met a problem where it is difficult to set AWS_PROFILE.

**Comment by samuelkarp** [comment]
@btsuhako's answer is correct.  Closing for now, feel free to reopen if you're having issues with that.
