### ISSUE TITLE
Token has expired

### ISSUE THREAD

**Issue by luizhpriotto** [awslabs/amazon-ecr-credential-helper#118]
Hello, how are you?

I'm using the Amazon linux (Amazon Linux AMI release 2018.03) and Docker Swarm (18.06.1-ce).

My docker-credential-ecr-login is "0.6.0".

This my config.json:

`{
    "credsStore":"ecr-login",
    "auths": {
        "########.dkr.ecr.sa-east-1.amazonaws.com": {
        }
    }
}`

I'm using root for operations... i can push and pull the images without "aws ecr get-login --no-include-email", but my workers cant pull new images, could you help me please?

This is the log in my Docker Worker.

`time="2018-10-23T18:02:42.616639182-03:00" level=error msg="Not continuing with pull after error: denied: Your Authorization Token has expired. Please run 'aws ecr get-login --no-include-email' to fetch a new one."
time="2018-10-23T18:02:42.616707624-03:00" level=error msg="pulling image failed" error="pull access denied for ######.dkr.ecr.sa-east-1.amazonaws.com/alegrafoods, repository does not exist or may require 'docker login'" module=node/agent/taskmanager node.id=x0oha0bylllzz996u03ce6vq5 service.id=txgklyldus42z8qdyubwj81rd task.id=hwgbcw81hp7km87vvh4hx6pec
time="2018-10-23T18:02:42.950647554-03:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint tp0m2soc0avdbh5zthxlvo2nb 23dabd833012f7b25481e22bb992408a19aae3df3b4a5f28f76df062823b1737], retrying....`

I restarted Docker daemon, but not work.

thanks so much!

**Comment by nayeemd** [comment]
is the config.json on worker having the auths.

**Comment by luizhpriotto** [comment]
I didnt know that i need to configure the credential helper im my managers too. 
Problem solved! sorry.
