### ISSUE TITLE
ARM support>?

### ISSUE THREAD

**Issue by fsamir** [awslabs/amazon-ecr-credential-helper#12]
This is more a suggestion than an issue. It would be nice to publish the binaries for most common platforms, so users don't have to bother building it themselves.

On the same token, I've tried to build it for arm without much success, most likely because this is my first contact with golang. 

This is what I am using in makefile -> make docker:

```
GOOS=linux
GOARCH=arm

docker run -e BUILD_GOOS="$(GOOS)" -e BUILD_GOARCH="$(GOARCH)" \
	-e OUTPUT=$(shell pwd)/bin \
	-v /var/run/docker.sock:/var/run/docker.sock \
	-v $(shell pwd)/ecr-login:/src centurylink/golang-builder-cross


```
Also, I had to add the following to ecr.go, to make the cross compiler docker image happy:

`package ecr // import "github.com/awslabs/amazon-ecr-credential-helper/ecr-login"
`

At the end ir produced a binary, but it doesn't seem to be executable on an ARM:

```
./docker-credential-ecr-login

/usr/local/bin/docker-credential-ecr-login: line 1: syntax error near unexpected token `newline'
/usr/local/bin/docker-credential-ecr-login: line 1: `!<arch>'
```

**Comment by samuelkarp** [comment]
@fsamir Thanks for opening this!  I've opened https://github.com/awslabs/amazon-ecr-credential-helper/pull/13 to make it easier to do cross-architecture compilation so you can build for ARM.

**Comment by samuelkarp** [comment]
@fsamir I've merged #13, so if you pull from master you should be able to build with `make docker TARGET_GOARCH=arm`.

**Comment by fsamir** [comment]
Thanks! I will give it a try.

**Comment by fsamir** [comment]
Working like a charm. Appreciated.
