### ISSUE TITLE
Token has expired again!

### ISSUE THREAD

**Issue by luizhpriotto** [awslabs/amazon-ecr-credential-helper#124]
Hi guys, I need your help and your experience.

I have a configured docker swarm, 3 managers and 3 workers.

I already have configured docker-credential-ecr. I can do the "push" perfectly in all nodes manager and also the workers. But when I try to update a new image I my cluster, I receive an error about “authentication expired” and my cluster is not updated.  If I do the “push” manually of the new image, my cluster is automatically updated without problens.

This is my versions:

Docker:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Tue Oct  2 18:06:45 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Tue Oct  2 18:08:26 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker-credential-ecr version:

`0.6.0`

This my configuration:

#docker-credential-ecr-login list
`{"https://052889732109.dkr.ecr.sa-east-1.amazonaws.com":"AWS"}`

#cat /root/.ecr/cache.json
`{
  "Registries": {
    "sa-east-1-QUtJQUpJQzRST0dGNEVaTFFEREHUHYzZjwCyBOmACZjs+EJ+-052889732109": {
      "AuthorizationToken": "QVd(…)Q==",
      "RequestedAt": "2018-11-02T20:04:40.083605807-03:00",
      "ExpiresAt": "2018-11-03T11:04:40Z",
      "ProxyEndpoint": "https://052889732109.dkr.ecr.sa-east-1.amazonaws.com"
    }
  },
  "Version": "1.0"
}
`

#cat /root/.docker/config.json
`{
        "credsStore": "ecr-login"
}
`

And this is my docker error log:

`time="2018-11-02T20:04:47.526969957-03:00" level=error msg="fatal task error" error="No such image: 052889732109.dkr.ecr.sa-east-1.amazonaws.com/alegrafoods:prod-1" module=node/agent/taskmanager node.id=2d6bqnwa9ml66yf8yj0o77pht service.id=lxoupnkvpykc0nal5fwhipf55 task.id=iuhtbe2m5raxgtah1sxxmmzjo
time="2018-11-02T20:04:48.751018971-03:00" level=warning msg="Error (Unable to complete atomic operation, key modified) deleting object [endpoint du1gtdxalyed18gzz5e2hhw0k 233c8fdb2cb9099fcda208f355e787afa6fec179ffecacd145bbcd39a122dcdc], retrying...."
time="2018-11-02T20:04:49.402474715-03:00" level=warning msg="failed to deactivate service binding for container sites_alegrafoods.2d6bqnwa9ml66yf8yj0o77pht.nnq5zuzlhpg09e5u9jbb2pynb" error="No such container: sites_alegrafoods.2d6bqnwa9ml66yf8yj0o77pht.nnq5zuzlhpg09e5u9jbb2pynb" module=node/agent node.id=2d6bqnwa9ml66yf8yj0o77pht
time="2018-11-02T20:04:50.315666336-03:00" level=error msg="Not continuing with pull after error: denied: Your Authorization Token has expired. Please run 'aws ecr get-login --no-include-email' to fetch a new one."
time="2018-11-02T20:04:50.315726623-03:00" level=error msg="pulling image failed" error="pull access denied for 052889732109.dkr.ecr.sa-east-1.amazonaws.com/alegrafoods, repository does not exist or may require 'docker login'" module=node/agent/taskmanager node.id=2d6bqnwa9ml66yf8yj0o77pht service.id=lxoupnkvpykc0nal5fwhipf55 task.id=ceetl7usvf2bqr81xb4q47dsz`

thanks so much.

**Comment by samuelkarp** [comment]
Hi @luizhpriotto,

I'm not very familiar with Docker Swarm, but my understanding is that Docker Swarm does not properly handle expired credentials properly.  Please see https://github.com/moby/moby/issues/31063 and https://github.com/docker/for-aws/issues/5 for some context.

Since I believe this is an issue with Docker Swarm and not an issue with the credential helper, I'm closing this issue.

Thanks!
Sam
