### ISSUE TITLE
make docker fails if outside of a git repo

### ISSUE THREAD

**Issue by russau** [awslabs/amazon-ecr-credential-helper#132]
Right now if I attempt to `make docker` from a tar download I get an error.

``` bash
$ curl -L https://github.com/awslabs/amazon-ecr-credential-helper/tarball/master  | tar xvz
$ cd awslabs-amazon-ecr-credential-helper-b9fd5a8/
$ make docker
find: `.git/': No such file or directory
mkdir -p bin
docker run --rm \
-e TARGET_GOOS= \
-e TARGET_GOARCH= \
-v '/home/ec2-user/ecr-credential-helper/awslabs-amazon-ecr-credential-helper-b9fd5a8/bin':/go/src/github.com/awslabs/amazon-ecr-credential-helper/bin \
sha256:b4d0f18b4b9041c84e79127226dee41c1fb3992e03ebb780b6b3e402c87443a7
find: '.git/': No such file or directory
git rev-parse --short=7 HEAD > GITCOMMIT_SHA
fatal: Not a git repository (or any of the parent directories): .git
Makefile:69: recipe for target 'GITCOMMIT_SHA' failed
make: *** [GITCOMMIT_SHA] Error 128
make: *** [docker] Error 2
```

This previously worked, e.g:

``` bash
$ curl -L https://github.com/awslabs/amazon-ecr-credential-helper/tarball/v0.1.0  | tar xvz
$ cd awslabs-amazon-ecr-credential-helper-95a58a5
$ make docker
fatal: Not a git repository (or any of the parent directories): .git
docker run --rm \
-e TARGET_GOOS= \
-e TARGET_GOARCH= \
-v '/home/ec2-user/ecr-credential-helper/awslabs-amazon-ecr-credential-helper-95a58a5/bin':/go/src/github.com/awslabs/amazon-ecr-credential-helper/bin \
sha256:eadf7295d089479df13447f64caf4ffcf77cfa8b1267c12a2ddc1c71fccffd27
fatal: Not a git repository (or any of the parent directories): .git
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local 0.1.0
Built ecr-login
```

**Comment by samuelkarp** [comment]
Thanks for opening this issue.  This was an unintended consequence of some build refactoring, so I'm marking it as a bug for now.

If you need to build outside of git, you have two options:

* Option 1: Clone the git repository and use `make release-tarball` to build a working tarball.  That tarball can be extracted and used to build without needing the whole git repository.
* Option 2: After downloading and extracting the tarball produced by GitHub, create a file named `GITCOMMIT_SHA` in the directory where the source was extracted.

**Comment by jkomyno** [comment]
@samuelkarp @russau Removing `$(GITFILES)` from the Makefile entry named `GITCOMMIT_SHA` worked for me. I'm running Windows 10 with Git Bash and GNU make. The command that I ran is `make windows-amd64`. Here the proposed edit to [Makefile](https://github.com/awslabs/amazon-ecr-credential-helper/blob/master/Makefile):

```diff
- GITCOMMIT_SHA: $(GITFILES)
+ GITCOMMIT_SHA:
	git rev-parse --short=7 HEAD > GITCOMMIT_SHA
```

**Comment by samuelkarp** [comment]
@jkomyno I'd prefer not to make that change, as it breaks the way that the Makefile is intended to work when run inside a git repository.  Instead, I'd like to release tarballs that contain the `GITCOMMIT_SHA` file, but it's (unfortunately) not very close to the top of my priority list.  In the meantime, I'd recommend the workarounds I suggested above.

**Comment by samuelkarp** [comment]
Tarballs with a correct `GITCOMMIT_SHA` file are now available.  You can find the tarball for v0.3.1 [here](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).
