### ISSUE TITLE
go install ecr credential is killing and time consuming -do we have python version of this util?

### ISSUE THREAD

**Issue by mkaja** [awslabs/amazon-ecr-credential-helper#133]
go install ecr credential is killing and time consuming -do we have python version of this util?

 setting gopath and goroot in both linux and mac is killing ....

**Comment by estahn** [comment]
@mkaja This is a duplicate of #80 

If this is for your local the following may be helpful: https://github.com/awslabs/amazon-ecr-credential-helper/issues/80#issuecomment-376140958

**Comment by samuelkarp** [comment]
Closing in favor of https://github.com/awslabs/amazon-ecr-credential-helper/issues/80
