### ISSUE TITLE
Doesn't work on latest docker version

### ISSUE THREAD

**Issue by alex88** [awslabs/amazon-ecr-credential-helper#135]
After installing the credential helper and trying to pull the image from the ecr registry:

```
root@ip-172-31-10-58:~# docker -v
Docker version 18.09.0, build 4d60db4
root@ip-172-31-10-58:~# cat .docker/config.json
{
	"credsStore": "ecr-login",
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.0 (linux)"
	}
}
root@ip-172-31-10-58:~# ecr-login
Usage: ecr-login <store|get|erase|list|version>
root@ip-172-31-10-58:~# docker pull xxx.dkr.ecr.us-west-1.amazonaws.com/xxx
Error response from daemon: Get https://xxx.dkr.ecr.us-west-1.amazonaws.com/v2/xxx/manifests/xxx: no basic auth credentials
```

seems it's not even trying to use the helper. There are no logs in `~/.ecr`

**Comment by FernandoMiguel** [comment]
Seems to be missing your account details

**Comment by alex88** [comment]
@FernandoMiguel seems in the background when actually using docker it was trying to call `docker-credential-ecr-login` not `ecr-login`, after copying the same file to both `ecr-login` and `docker-credential-ecr-login` it worked :/
