### ISSUE TITLE
"no basic auth credentials"

### ISSUE THREAD

**Issue by kilianc** [awslabs/amazon-ecr-credential-helper#14]
I am running on CoreOS and after compiling and copying the binary and following steps [here](https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/) I keep getting the same error:

    Error response from daemon: Get https://xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/<some>/<image>/manifests/latest: no basic auth credentials

Even when I export `AWS_ACCESS_KEY_ID` `AWS_SECRET_ACCESS_KEY` or put them inline

**Comment by kilianc** [comment]
Figured out. I had to run on docker `.11` which is only available on coreos-beta ATM.
Thanks!

**Comment by samuelkarp** [comment]
Glad you were able to get it working!

**Comment by guyisra** [comment]
Using Docker version 17.05.0-ce, build 89658be I also get no basic auth credentials even though the env vars are defined..
