### ISSUE TITLE
"No such image:" error still occurs in AWS docker swarm setup

### ISSUE THREAD

**Issue by lybroman** [awslabs/amazon-ecr-credential-helper#140]
I have followed the doc to setup the amazon-ecr-credential-helper automatically in launch configuration user data for swarm node ec2 instances. When I ssh to the newly created node, i could pull any image in the ecr. However the service update or stack deploy would still show "No such image:" error. If I pull the image manually, the service container could be launched correctly on that node.

**Comment by samuelkarp** [comment]
I don't believe that Docker Swarm can use credential helpers.  See https://github.com/moby/moby/issues/31063 for more details.
