### ISSUE TITLE
Publish compiled binary as github releases

### ISSUE THREAD

**Issue by kilianc** [awslabs/amazon-ecr-credential-helper#15]
It would be very helpful to be able to fetch the binary from github!

**Comment by lox** [comment]
Yeah, or at the very least make this `go get`-able.

**Comment by samuelkarp** [comment]
@lox You can `go get github.com/awslabs/amazon-ecr-credential-helper/...`.

**Comment by kilianc** [comment]
@samuelkarp I ended up using:

```
cat << EOF > /opt/bin/docker-credential-ecr-login
#!/bin/sh

SECRET=\\$(docker run --rm \\
  -e "METHOD=\$1" \\
  -e "REGISTRY=\$(cat -)" \\
  -e "AWS_ACCESS_KEY_ID=..." \\
  -e "AWS_SECRET_ACCESS_KEY=..." \\
  pottava/amazon-ecr-credential-helper)

echo \$SECRET | grep Secret
EOF
chmod +x /opt/bin/docker-credential-ecr-login
```

**Comment by lox** [comment]
@samuelkarp wouldn't that install a `cmd` binary?

**Comment by samuelkarp** [comment]
@lox Yes, you'll need to rename it to `docker-credential-ecr-login` and place it in your `PATH`.

**Comment by lox** [comment]
Wouldn't a better approach be to add a subdir of cmd called `docker-credential-ecr-login`?

**Comment by willejs** [comment]
Can you cut a release and a binary?

**Comment by H2so4** [comment]
+1 for binaries for each platform supported

**Comment by lox** [comment]
It's pretty annoying that this project is such a pain to consume, especially with Amazon recommending it as the alternative to `aws ecr get-login` in a few places. @samuelkarp what's the thinking behind not offering binaries or following go best practices around making it go-gettable?

**Comment by bernardoVale** [comment]
Please, cut a release!! It will take two minutes of your time.

**Comment by lox** [comment]
It's annoying, but there is a brew that automates some of this at brew install https://raw.githubusercontent.com/winebarrel/homebrew-docker-credential-ecr-login/master/docker-credential-ecr-login.rb

**Comment by lox** [comment]
I got fed up, so I've forked the project and I will offer releases at https://github.com/lox/amazon-ecr-credential-helper/releases/tag/v1.0.0

**Comment by danielcompton** [comment]
This is also a pain in CI, as I would like to be able to deploy docker images from CI, but there isn't an easy package to download to do this.

**Comment by Jalle19** [comment]
I ended up building this locally, then `scp` the file over to the target server. At the very least, instructions on how to `go build` the binary without Docker would be appreciated.

**Comment by lox** [comment]
@Jalle19 my PR was merged recently, so you can just:

```bash
go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
```

(See https://github.com/awslabs/amazon-ecr-credential-helper#installing)

**Comment by Jalle19** [comment]
@lox I did run that but I couldn't find the binary. Maybe it's too early in the morning...

**Comment by lox** [comment]
It will install it in $GOBIN, check out `go env`. Failing that, clone the repo and run `make build`.

**Comment by lox** [comment]
One day we will convince @samuelkarp to cut release binaries ;)

**Comment by Jalle19** [comment]
Thanks for the tips!

**Comment by singingwolfboy** [comment]
I tried to write a Homebrew formula for this, and was told that [it won't be accepted unless there is an actual release](https://github.com/Homebrew/homebrew-core/pull/18914).

**Comment by lobsterdore** [comment]
You would be doing the community a huuuuuge favour by making this happen!

**Comment by samuelkarp** [comment]
Closing in favor of https://github.com/awslabs/amazon-ecr-credential-helper/issues/80, which is tracking the work necessary for this to happen.
