### ISSUE TITLE
Issues installing on ubuntu

### ISSUE THREAD

**Issue by ucancprem** [awslabs/amazon-ecr-credential-helper#153]
We are having issues installing `amazon-ecr-credential-helper` on ubuntu 14 machines( AWS codebuild).

Is there anyway you could document installing this on Ubuntu 14 ?

**Comment by samuelkarp** [comment]
Binary releases are now available.  You can find the link to v0.3.1 [here](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).
