### ISSUE TITLE
[feature request] relax the restriction docker-credential-ecr-login can only be used with Amazon Elastic Container Registry.

### ISSUE THREAD

**Issue by sonots-zozo** [awslabs/amazon-ecr-credential-helper#155]
I got an error like:

```
Unable to find image 'ruby:2.5.1' locally
time="2019-02-12T18:17:16+09:00" level=error msg="Error parsing the serverURL" error="docker-credential-ecr-login can only be used with Amazon Elastic Container Registry." 
```

I want to use dockerhub in addition to ECR even when I use amazon-ecr-credential-helper.

**Comment by sonots-zozo** [comment]
sorry, i found that https://github.com/awslabs/amazon-ecr-credential-helper#configuration

```
{
	"credHelpers": {
		"aws_account_id.dkr.ecr.region.amazonaws.com": "ecr-login"
	}
}
```

is available, and the docker pull command actually succeeds although I got the error messages.

**Comment by engmsaleh** [comment]
It didn't solve the problem with me
I'm using `Docker version 18.09.1, build 4c52b90`
