### ISSUE TITLE
Docker API integration with credential helpers

### ISSUE THREAD

**Issue by alex131290** [awslabs/amazon-ecr-credential-helper#156]
I have installed the `docker-credential-ecr-login`, i've added `~/.docker/config.json` which holds all the ECR repos that i need access to. Whenever i'm trying to use the `Docker API` to pull an image from one of the repositories which configured in the config.json, i'm getting an error
`curl --unix-socket /var/run/docker.sock   -X POST "http:/v1.35/images/create?fromImage=015895086574.dkr.ecr.us-east-1.amazonaws.com/mss_worker_dev"
{"message":"Get https://015895086574.dkr.ecr.us-east-1.amazonaws.com/v2/mss_worker_dev/tags/list: no basic auth credentials"}` .
If i'm doing the same thing  through the `Docker CLI` it's working.

**Comment by samuelkarp** [comment]
Hi @alex131290,

Unfortunately, the Docker API does not make use of credential helpers or of any entries present in `~/.docker/config.json`.  If you're using the Docker API, you'll need to pass the credential data as part of the request to `$version/images/create`.  See the [API documentation](https://docs.docker.com/engine/api/v1.37/#section/Authentication) for more detail.

Thanks,
Sam
