### ISSUE TITLE
How can we install on CoreOS?

### ISSUE THREAD

**Issue by doron-levi** [awslabs/amazon-ecr-credential-helper#160]

**Comment by kcraley** [comment]
@doron-levi - Ran into the same issue and have compiled the binary from source.  Then, I am vendoring it into a repository which uploads all dependencies for Ignition into an S3 bucket.  

Ideally, it would be nice to have a public location to pull the binary from that way the URL can be specified inside Container Linux Config/Ignition.

**Comment by samuelkarp** [comment]
Binary releases are now available.  You can find the links to v0.3.1 [here](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).
