### ISSUE TITLE
Docker push to ECR not working

### ISSUE THREAD

**Issue by venkat2286** [awslabs/amazon-ecr-credential-helper#166]
The push refers to repository [xxxxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/test]
bc0967eecd77: Preparing
35c20f26d188: Preparing
c3fe59dd9556: Preparing
6ed1a81ba5b6: Preparing
a3483ce177ce: Preparing
ce6c8756685b: Preparing
30339f20ced0: Preparing
0eb22bfb707d: Preparing
a2ae92ffcd29: Preparing
no basic auth credentials

- I tried all possible option like aws configure ...aws ecr get-login with region  but push not working.
- aws ecr describe-repositories is giving the right repository name which is confirming that it is pointing to right repository.

**Comment by samuelkarp** [comment]
Hello, `aws ecr get-login` is a command of the AWS CLI, not the credential helper.  If you're looking for help with the AWS CLI, you can find their repository [here](https://github.com/aws/aws-cli/).  I'm closing this issue, but if you do install and configure the credential helper and run into issues, feel free to reopen this or open a new one.

**Comment by rsibanez89** [comment]
Is this solved?
```
# doing:
aws ecr get-login --region=sa-east-1
docker push xxxxxxxxxxxxxxx.dkr.ecr.sa-east-1.amazonaws.com/venko:latest

# I get
aws ecr get-login --region=sa-east-1
docker login -u AWS -p xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -e none https://xxxxxxxxxxxxxxx.dkr.ecr.sa-east-1.amazonaws.com
docker push xxxxxxxxxxxxxxx.dkr.ecr.sa-east-1.amazonaws.com/venko:latest
The push refers to repository [xxxxxxxxxxxxxxx.dkr.ecr.sa-east-1.amazonaws.com/venko]
538f89b7eec5: Preparing
be80b4178fb5: Preparing
a28cc03a5e2b: Preparing
4886971656ba: Preparing
5fd7263f6a02: Preparing
83fd01259bab: Preparing
2d1366b57196: Waiting
ff950eb7ad79: Preparing
3be0c4da2073: Preparing
ad32e728de9a: Preparing
5216338b40a7: Preparing
no basic auth credentials
```
