### ISSUE TITLE
Doesn't observe profiles for AWS credentials

### ISSUE THREAD

**Issue by djb61** [awslabs/amazon-ecr-credential-helper#17]
I have a number of AWS accounts with keys for each. To work with these I have configured them as profiles with the CLI using `aws configure --profile=xxxx`

In this case the entries in `~/.aws/credentials` appear in a block of `[profilename]` instead of the usual `[default]`.

I do not have a `[default]` block in my credentials file at all and with the CLI I use the `AWS_DEFAULT_PROFILE` environment variable to state the profile to use when none is explicitly stated on the command line.

Using the credential helper with my setup it fails to authenticate with ECR. If however I edit my credentials file and change the heading block for the profile of the account the ECR resides in to `[default]` then it works. This suggests the tool does not observe the default profile environment variable the CLI uses.

This does open the wider question of how to deal with multiple accounts using ECR, fortunately I do not have to worry about that myself yet as only one of my accounts is running ECR at the moment.

**Comment by samuelkarp** [comment]
@djb61 You can change the profile used by the credential helper by setting the `AWS_PROFILE` environment variable.

For example: `AWS_PROFILE=myprofile docker pull 137112412989.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:latest`

**Comment by djb61** [comment]
Thanks, that does indeed work. It is a bit more tedious when I only have ECR with one account but I can see that it does make sense and addresses the question of working with ECR across multiple accounts.

**Comment by samuelkarp** [comment]
Glad it's working for you. :smile:
