### ISSUE TITLE
apt install error in mint

### ISSUE THREAD

**Issue by sajusat** [awslabs/amazon-ecr-credential-helper#174]
Linux MintVM 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

sudo apt update

sudo apt install amazon-ecr-credential-helper

got error 

      E: Unable to locate package amazon-ecr-credential-helper

**Comment by samuelkarp** [comment]
The credential helper is not currently available in the Linux Mint repositories.  You can download the v0.3.1 binaries [here](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).
