### ISSUE TITLE
`make docker` does not write anything to bin/

### ISSUE THREAD

**Issue by djm-healx** [awslabs/amazon-ecr-credential-helper#175]
Evening,

I have been trying to create the binary on Windows Linux Subsystem (Ubuntu 18.04) using Docker for Windows (up to date), since I cannot install `amazon-ecr-credential-helper` directly from the Ubuntu package registry.

While `make docker` appears to run just fine, nothing is actually written to the `bin` directory in the repository. However, I did notice that the timestamp for `bin` becomes updated, so it must be doing something... am I missing something obvious?

**Comment by igorpdasilvaa** [comment]
Hi, `make docker` make the output of binary in you local folder so if you are in `/home/user/amazon-ecr-credential-helper` and run the make docker the binary will be in this folder and not in the bin folder

**Comment by igorpdasilvaa** [comment]
make docker output the binary in you local folder and not in the bin, check the folder of the project

**Comment by djm-healx** [comment]
> make docker output the binary in you local folder and not in the bin, check the folder of the project

The binary is not anywhere to be seen unfortunately.

**Comment by samuelkarp** [comment]
@djm-healx What output do you see when you run `make docker`?

If you prefer to just download a prebuilt binary, you can find the links on the [v0.3.1 release](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).

**Comment by samuelkarp** [comment]
Closing this since we haven't heard back from you.  If you're still running into this issue, please feel free to reopen it.  Thanks!
