### ISSUE TITLE
Swarm service "No such image"

### ISSUE THREAD

**Issue by igorpdasilvaa** [awslabs/amazon-ecr-credential-helper#176]
In a  swarm cluster i need to run a service create with `--with-registry-auth`, fine but if my node become offline the swarm can't up a new container in any other node giving the `no such image`
In all nodes i can use the docker pull in the image and work fine but the service can't do this automatically 
Anyone know how to solve this ?

**Comment by samuelkarp** [comment]
Hi, I'd recommend opening this issue on the Swarm repository instead.  I don't have enough familiarity with Swarm to be able to help.
