### ISSUE TITLE
Windows build resulting in Windows Defender catch

### ISSUE THREAD

**Issue by richardgavel** [awslabs/amazon-ecr-credential-helper#178]
I created a Windows build (since none is provided) and Windows Defender is catching the resulting EXE. Can you either publish a Windows EXE so we have something that is trusted or validate none of the libraries that would be referenced contains this issue.

![image](https://user-images.githubusercontent.com/3877391/62893459-4ff39280-bd10-11e9-8a2c-f8f4cd0e0f3c.png)

**Comment by samuelkarp** [comment]
A Windows executable is available for download [here](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1).

I have attempted to reproduce the issue that you've reported on Windows Server 2019, both with the Windows executable linked above and by compiling from scratch, and have been unable to do so.

In the future, if you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).
