### ISSUE TITLE
Unable to use "credsStore" and "auths" at the same time

### ISSUE THREAD

**Issue by usamaahmadkhan** [awslabs/amazon-ecr-credential-helper#187]
I'm unable to login into docker.io registry when i use **ecr-login** with credsStore.
Here is my config.json:
```
{
        "auths": {
                "docker.domain.com:443": {
                        "auth": "BASE64STRING"
                },
                "https://index.docker.io/v1/": {
                        "auth": "BASE64STRING"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/17.09.1-ce (linux)"
        },
        "credsStore": "ecr-login"
}
```
When I push to ECR it works completely fine. But when I do `docker push docker.io/<image>:<tag>` it gives
> denied: requested access to the resource is denied

**DEBUGGING:**
I tried to do `docker login docker.io` with the above configuration and it gives the following error:
>Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`

Docker : 18.09.7
docker-credential-ecr-login: 0.3.1

**Comment by samuelkarp** [comment]
I don't believe Docker supports using "credsStore" and "auths" (with the base64-encoded username/password pair) together.  Docker does support using "credHelpers" for specific, named registries; you can try to specify a different credential helper for "docker.domain.com" and "index.docker.io".  If you continue to have trouble with that or if you have feature requests for Docker, I suggest opening issues on [the moby/moby repo](https://github.com/moby/moby).
