### ISSUE TITLE
Release New Version

### ISSUE THREAD

**Issue by Teddy-Schmitz** [awslabs/amazon-ecr-credential-helper#192]
Hi,

Would it be possible to cut and tag a new release?  The last version is from July 8, 2019 and since then `sts:AssumeRoleWithWebIdentity` was released.  While this was fixed in this repo no-one downstream can use it from a regular `go get` until a new version is released and tagged.  This is preventing projects like [GoogleContainerTools/kaniko](https://github.com/GoogleContainerTools/kaniko) from working properly on EKS with RBAC IAM credentials.

Thank you!

**Comment by markus7811** [comment]
Please try to set the environment variable AWS_SDK_LOAD_CONFIG=true
