### ISSUE TITLE
Enable shared config by default

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/amazon-ecr-credential-helper#198]
Currently, the behavior of the AWS SDK for Go is to ignore the shared config file (`~/.aws/config`) unless explicitly enabled and the credential helper inherits this behavior.  The shared config file is not explicitly enabled in the credential helper today, but can be enabled by setting the environment variable `AWS_SDK_LOAD_CONFIG=true`.  It would be better to enable the shared config by default, and allow it to be disabled by `AWS_SDK_LOAD_CONFIG=false` if desired.

**Comment by andrewsharon** [comment]
I'm going to look into making this change.
