### ISSUE TITLE
How to configure this tool for all users on an instance except configuring ~/.docker/config.json for each user? 

### ISSUE THREAD

**Issue by gengmao** [awslabs/amazon-ecr-credential-helper#2]
This tool works great! I suppose I don't need worry about the rate limit of `aws ecr get-login` any more, right? 

Also I am curious is there a way to configure this tool for all users on an instance, without setting ~/.docker/config.json for each user? Thanks!

**Comment by samuelkarp** [comment]
Hi @gengmao,

The credential helper does not cache credentials today, so the rate limit for `GetAuthorizationToken` can still be a concern if you're pushing/pulling with high frequency.

I believe Docker's credential configuration is per-user today, so you will need to set it in `~/.docker/config.json` for each user.

Thanks,
Sam

**Comment by gengmao** [comment]
@samuelkarp Thanks for your prompt answer. If I understand your words correctly, using this tool means each docker pull/push will trigger a `GetAuthorizationToken` request? 
Will this increase the request rate of `GetAuthorizationToken`, as without this tool docker pull/push will use the token stored in ~/.docker/config.json, we don't need to get a new token until it expires?

**Comment by samuelkarp** [comment]
Yes, each `docker push`/`docker pull` will trigger a `GetAuthorizationToken` request.  As you mention, this is different from how a token can be stored in `~/.docker/config.json` when using the default credential behavior in Docker.

**Comment by gengmao** [comment]
I see. Maybe I will stay with old way for now, to avoid cause too many 'GetAuthorizationToken' request to ECR. 
Btw I learned DOCKER_CONFIG can be used to let docker find config.json. I am closing this issue, thanks again!

**Comment by samuelkarp** [comment]
@gengmao: @sentientmonkey just added caching via #3, so that should hopefully address your concern about the request rate to `GetAuthorizationToken`.
