### ISSUE TITLE
Version inconsistent with release

### ISSUE THREAD

**Issue by jpigree** [awslabs/amazon-ecr-credential-helper#206]
Output of ```docker-credential-ecr-login version``` when using **v0.4.0** binary [release](https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/0.4.0/linux-amd64/docker-credential-ecr-login):
`0.6.3`

I don't understand. Do I miss something?
I tried the 0.3.1 binary release aswell and the output is **0.6.0**.

**Comment by samuelkarp** [comment]
The `version` subcommand returns the version of Docker credential helper spec (defined [here](https://github.com/docker/docker-credential-helpers/blob/f78081d1f7fef6ad74ad6b79368de6348386e591/credentials/version.go#L4)).  You can find the version for this credential helper using the `-v` flag: `docker-credential-ecr-login -v`.

This is documented in the manual page [here](https://github.com/awslabs/amazon-ecr-credential-helper/blob/68cfee07af64dcc2a171c20eb6f3e13e9550920a/docs/docker-credential-ecr-login.1#L84-L85) and [here](https://github.com/awslabs/amazon-ecr-credential-helper/blob/68cfee07af64dcc2a171c20eb6f3e13e9550920a/docs/docker-credential-ecr-login.1#L99-L100), but I'm happy to take pull requests that document this more clearly as well.

**Comment by jpigree** [comment]
Okay. I was pretty sure I was missing something. Thanks for the quick explanation.

**Comment by whereisaaron** [comment]
For a gazillion (give or take) other tools `version` returns the version of the tool and not the version of one library dependency 😄 This was a really poor decision by Docker. Could the usage text try to warn the user?

```
$ docker-credential-ecr-login
Usage: docker-credential-ecr-login <store|get|erase|list|version>
IMPORTANT: 'version' is not the version of docker-credential-ecr-login but the version of the docker library it uses.
Use '-v' to get the version of docker-credential-ecr-login.
```
