### ISSUE TITLE
The ability to automatically create an ECR repo when executing a Docker push

### ISSUE THREAD

**Issue by nbrandaleone** [awslabs/amazon-ecr-credential-helper#209]
Currently, it is required for a repository to exist within ECR before it accepts a Docker push.
It would be a powerful feature if the ECR helper would check to see if a repo exists, and if not, automatically create it and then execute the Docker push command. 

This could be the default action or enabled using a command line flag.

**Comment by samuelkarp** [comment]
Thanks for opening this, but I think the request would generally be better for the [containers roadmap](https://github.com/aws/containers-roadmap).  Create-on-push would be an ECR feature.

I don't think we should implement create-on-push in the credential helper for a few reasons:
* Create-on-push is a generally useful feature that would help customers of ECR, regardless of how they manage authentication data.  Implementing it in the credential helper benefits only a subset of ECR customers.
* The credential helper is a very small, focused tool: it does authentication, and nothing else.  Adding a feature like this increases the surface area for testing and maintenance.
* Aside from eliminating the requirement to use `docker login`, customers who use the credential helper interact with Docker and ECR the same as any other authentication mechanism.  Introducing a feature like this introduces another behavior that customers may find confusing: sometimes create-on-push works (i.e., when they use the credential helper) and sometimes it doesn't.  This is a non-obvious behavior change just from using the credential helper.
* From a technical perspective, the credential helper can't actually do this.  The credential helper protocol doesn't define precisely what input the helper gets (it specifies a [`ServerURL`](https://github.com/docker/docker-credential-helpers/blob/f78081d1f7fef6ad74ad6b79368de6348386e591/credentials/credentials.go#L15), but doesn't define what that contains).  In practice, Docker only sends the beginning of a URL (the scheme + domain name) like "https://index.docker.io/v1/" or "https://12345678012.dkr.ecr.us-east-1.amazonaws.com".  This means that the credential helper doesn't know the repository name.
* From a technical perspective, the credential helper can't distinguish between pull and push.  It would be undesirable to create a repository when you try to pull, but the credential helper can't know which action is being performed.
* From a technical perspective, it's hard to conditionally enable features like this.  We can't add flags, as the command-line invocation is controlled by the credential helper protocol (the Docker CLI invokes the credential helper directly, with a set interface).  The only way to pass dynamic configuration through is environment variables (like `AWS_PROFILE`).  The credential helper *could* grow the ability to have a config file with defaults defined there, but does not presently have such a capability.

I'm going to close this issue as I don't think the credential helper is the right place to implement this feature.
