### ISSUE TITLE
How does this work with Docker Desktop Kubernetes

### ISSUE THREAD

**Issue by AceHack** [awslabs/amazon-ecr-credential-helper#210]
Inside docker desktop kubernetes it is not using these credentials.

**Comment by samuelkarp** [comment]
Hi @AceHack.  Unfortunately I'm not very familiar with Docker Desktop or its Kubernetes integration.  However, my understanding is that generally Kubernetes handles credentials independently of Docker.  According to the [Kubernetes documentation](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry):

> Note: Kubernetes as only supports the auths and HttpHeaders section in Docker configuration. Docker credential helpers (credHelpers or credsStore) are not supported.

**Comment by samuelkarp** [comment]
There's active work going on in the Kubernetes community to add support for out-of-process credential providers: https://github.com/kubernetes/kubernetes/pull/94196.  Closing this issue; you can follow that pull request.
