### ISSUE TITLE
ecr custom domain

### ISSUE THREAD

**Issue by GwonsooLee** [awslabs/amazon-ecr-credential-helper#224]
We have trouble in using kaniko with amazon-ecr because we useed custom ecr domain name
But, because of this ecrPattern check, it is not possible to login.

Is there any other way to fix this problem?

```
var ecrPattern = regexp.MustCompile(`(^[a-zA-Z0-9][a-zA-Z0-9-_]*)\.dkr\.ecr(\-fips)?\.([a-zA-Z0-9][a-zA-Z0-9-_]*)\.amazonaws\.com(\.cn)?`)
```
https://github.com/awslabs/amazon-ecr-credential-helper/blob/68cfee07af64dcc2a171c20eb6f3e13e9550920a/ecr-login/api/client.go#L34

**Comment by samuelkarp** [comment]
This request is being tracked in https://github.com/awslabs/amazon-ecr-credential-helper/issues/94 and in https://github.com/aws/containers-roadmap/issues/299.  Closing this issue in favor of those.
