### ISSUE TITLE
IRSA doesn't work with 0.4.0

### ISSUE THREAD

**Issue by missedone** [awslabs/amazon-ecr-credential-helper#234]
per the release notes 0.4.0 
* Feature - Added support for Web Identities and IAM Roles for Service Accounts (IRSA) with Kubernetes (#183)
https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.4.0

however it doesn't work, i see err in `~/.ecr/log/ecr-login.log`
> time="2020-08-09T10:58:07-07:00" level=debug msg="Retrieving credentials" region=us-west-2 registry=511263661634 serverURL=511263661634.dkr.ecr.us-west-2.amazonaws.com
time="2020-08-09T10:58:07-07:00" level=debug msg="Calling ECR.GetAuthorizationToken" registry=511263661634
time="2020-08-09T10:58:07-07:00" level=error msg="Error retrieving credentials" error="ecr: Failed to get authorization token: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"

recompile from master branch works.
so pls create a new release.

**Comment by itssimon** [comment]
Setting the following environment variables made it work for me:

```
AWS_EC2_METADATA_DISABLED: true
AWS_SDK_LOAD_CONFIG: true
```

Would be good if this was documented properly.

**Comment by missedone** [comment]
it should be default behavior on supporting IRSA, EC2 iam, etc.
so i think it's a bug, anyway build from master branch works as expected.

**Comment by Nuru** [comment]
Noticing the same behavior with v0.4.0, although in my case there is no `~/.aws/config` file. I have a Kubernetes Pod effectively using an IAM Role for Service Accounts with other AWS tools, but this tool uses the EC2 instance role, not the service account role.

**Comment by samuelkarp** [comment]
The next release is expected to default `AWS_SDK_LOAD_CONFIG` to `true`.

**Comment by samuelkarp** [comment]
This should now be fixed in [v0.5.0](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.5.0).
