### ISSUE TITLE
Support for Ubuntu 16.04 and 18.04

### ISSUE THREAD

**Issue by mmuppidi** [awslabs/amazon-ecr-credential-helper#235]
Many Enterprise users are still using 16.04 and 18.04 flavors of Ubuntu. credential helper needs to support these versions of operating systems as well.

**Comment by awilkins** [comment]
It's a Go program ; it's statically linked and has no runtime dependencies, there's no reason why it wouldn't work on 18.04 or 16.04.

You should in theory just be able to download the deb file and unpack the executable to `~/.local/bin`

**Comment by samuelkarp** [comment]
Hello, this request is tracked in https://github.com/awslabs/amazon-ecr-credential-helper/issues/188.  Closing as a duplicate.
