### ISSUE TITLE
Homebrew formula is out-of-date

### ISSUE THREAD

**Issue by pikeas** [awslabs/amazon-ecr-credential-helper#236]
```
$ brew info docker-credential-helper-ecr
docker-credential-helper-ecr: stable 0.4.0 (bottled)
```

**Comment by samuelkarp** [comment]
The [Homebrew formula](https://formulae.brew.sh/formula/docker-credential-helper-ecr) now packages [the most recent release](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.5.0).
