### ISSUE TITLE
Windows 10 running aws ecr docker login

### ISSUE THREAD

**Issue by ryshiselect** [awslabs/amazon-ecr-credential-helper#239]
Error:

Error saving credentials: error storing credentials - err: exit status 1, out: `not implemented`

I am using azure login as well to connect to our AWS

**Comment by samuelkarp** [comment]
Hi @ryshiselect! The credential helper does not require you to run `aws ecr get-login` or `aws ecr get-login-password`.  Please see the [usage instructions](https://github.com/awslabs/amazon-ecr-credential-helper/blob/master/README.md#usage).  I'm going to close this issue, but please feel free to open a new issue if you have any further questions.
