### ISSUE TITLE
Storing cached credentials in macOS keychain instead of ~/.ecr/cache.json

### ISSUE THREAD

**Issue by vroad** [awslabs/amazon-ecr-credential-helper#276]
It's not very secure to store cached credentials in json file. Could we store it in keychain instead on macOS, instead of disabling credentials cache completely with `AWS_ECR_DISABLE_CACHE`?

If it's secure enough to store credentials on disk, then why does default credential helper of Docker Desktop on mac store credentials in macOS keychain?

**Comment by samuelkarp** [comment]
> If you think you’ve found a potential security issue, please do not post it in the Issues. Instead, please follow the instructions [here](https://aws.amazon.com/security/vulnerability-reporting/) or [email AWS security directly](mailto:aws-security@amazon.com).

https://github.com/awslabs/amazon-ecr-credential-helper#security-disclosures
