### ISSUE TITLE
"no basic auth credentials" with "docker build"

### ISSUE THREAD

**Issue by alexandrud** [awslabs/amazon-ecr-credential-helper#288]
Hi,

Although "docker pull" and "docker push" work, if you run "docker build" and the base image needs to get pulled from ECR, you will get the error: "no basic auth credentials".

Steps to reproduce:
- make sure you're not logged in with ECR already
- create a .dockerfile with a base image in ECR
- run docker build 

Environment:
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Amazon
Description:    Amazon Linux release 2 (Karoo)
Release:        2
Codename:       Karoo

rpm -qa | grep ecr
amazon-ecr-credential-helper-0.5.0-1.amzn2.x86_64

**Comment by samuelkarp** [comment]
Hi @alexandrud, this is a known limitation.  https://github.com/awslabs/amazon-ecr-credential-helper/issues/251 is the tracking issue for adding some better documentation and has some additional background and workarounds.

I'm going to close this issue and will continue to use https://github.com/awslabs/amazon-ecr-credential-helper/issues/251 to track.
