### ISSUE TITLE
ecr cred helper is not working 100% of the time

### ISSUE THREAD

**Issue by Brett55** [awslabs/amazon-ecr-credential-helper#29]
I'm finding that when an EC2 spins up, and does a docker pull from ECR, I sometimes get:

"unauthorized: authentication required"

On a second attempt, it pulls the image down. Is there some "init" that needs to occur before it works all the time?

**Comment by Brett55** [comment]
I can confirm its failing randomly, sometimes it works sometimes it doesn't. There is on first time pulling from ECR. It is not after x amount of time, etc

**Comment by gengmao** [comment]
@Brett55 What are your docker engine version, ecr-login git commit id and .docker/config.json? When you hit error, did ~/.ecr/cache.json exist and what are the messages in ~/.ecr/log/ and docker engine's log?

**Comment by samuelkarp** [comment]
@Brett55 Can you provide the logs that are generated in `~/.ecr/log` from the period where you're seeing authentication failures?

**Comment by Brett55** [comment]
@gengmao @samuelkarp 

here is the output from docker version:

```Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.3
 Git commit:   b9f10c9/1.11.2
 Built:        
 OS/Arch:      linux/amd64```

I'm having some trouble getting the logs but basically about 10% of boxes fail to deploy because they get "unauthorized: authentication required" error when pulling a test image (alpine hosted on ecr). It works for the most part but fails typically on the first pull of a fresh EC2

**Comment by Brett55** [comment]
@gengmao @samuelkarp 

Also, the reason I switched to using the ecr cred helper was because we are getting rate limited when getting an auth token. Is the standard response when that happens this "unauthorized: authentication required"

**Comment by sentientmonkey** [comment]
@Brett55 that is the error message that you'd receive if the cred helper was unable to provide credentials. But, without the logs from ~/.ecr/logs and specific git commit id of the credential helper their is not much that we can go on to help troubleshoot or reproduce your issue.

**Comment by Brett55** [comment]
@sentientmonkey

**Comment by Brett55** [comment]
When I get "unauthorized: authentication required", there is no cache.json
 
`[stderr]/root/.ecr/cache.json: No such file or directory`

**Comment by samuelkarp** [comment]
@Brett55 We need to see the logs in order to know what's going on.  You'll find them in `~/.ecr/log` after a failure occurs.

**Comment by rossmckelvie** [comment]
I have a cache.json file, and receive this same authentication required error on one of my jenkins builds. Our installation date of this helper was Jan 11, 2017 so a little out of date. Other builds worked without issue, and the base image we were trying to pull down hadn't been modified since the last success.

My ecr log file looks clean:
```
2017-04-26T15:37:17Z [DEBUG] Retrieving credentials for MY_AWS_ID in us-east-1 (MY_AWS_ID.dkr.ecr.us-east-1.amazonaws.com)
2017-04-26T15:37:17Z [DEBUG] GetCredentials for MY_AWS_ID
2017-04-26T15:37:17Z [DEBUG] Checking file cache for MY_AWS_ID
2017-04-26T15:37:17Z [DEBUG] Using cached token for MY_AWS_ID
```
The logs are identical for other builds that succeed. We have double checked that our ecr repo/tag path is correct.

I upgraded to the latest version of the helper this morning and restarted jenkins, and it resolved the issue for us. I will follow up if I encounter this again on the latest version

**Comment by samuelkarp** [comment]
@Brett55 We haven't heard back from you in a while, so I'm going to close this issue.  If you're able to provide us with logs, we can investigate what's happening.
