### ISSUE TITLE
Is the Docker Engine dependency a necessity?

### ISSUE THREAD

**Issue by jetxr** [awslabs/amazon-ecr-credential-helper#322]
I'm using Docker CLI in an Alpine container on Host A to remotely control Docker Engine on Host B

In this case, I don't really need Docker Engine on Host A. But since i'm using ECR, I need to add amazon-ecr-credential-helper to Host A. And, amazon-ecr-credential-helper adds `docker` package as [a dependency](https://pkgs.alpinelinux.org/package/edge/community/aarch64/docker-credential-ecr-login). This adds overhead to the container on Host A.

I went through the source quickly, and it doesn't look like Docker Engine was being used. Is it possible to drop `docker` as dependency and maybe just have [`docker-cli`](https://pkgs.alpinelinux.org/package/edge/community/x86/docker-cli) as a dependency instead?

This would make for lower footprint on installs which don't need Docker Engine.

**Comment by kzys** [comment]
Makes sense for me. For example, our Amazon Linux 2 package doesn't depend on Docker Engine.

https://github.com/awslabs/amazon-ecr-credential-helper/blob/amazonlinux/amazon-ecr-credential-helper.spec

That being said, the Alpine package is managed by the Alpine community, not ourselves. You may need to contact the package maintainer.

**Comment by jetxr** [comment]
Got it, will get in touch with the Alpine community. Thanks!
