### ISSUE TITLE
Any plan to add a project version with git tags?

### ISSUE THREAD

**Issue by kencochrane** [awslabs/amazon-ecr-credential-helper#33]
Is there any plans to add a project version, with associated git tags? Or should we always build from master assuming it will always be stable?

**Comment by mathewpeterson** [comment]
We also would like to see this project use tags/releases.

**Comment by samuelkarp** [comment]
Closing in favor of https://github.com/awslabs/amazon-ecr-credential-helper/issues/80, which is tracking the work necessary for this to happen.
