### ISSUE TITLE
How to use with a multi-profile ~/.aws/config?

### ISSUE THREAD

**Issue by rvandegrift** [awslabs/amazon-ecr-credential-helper#34]
Is there a way to configure the credential helper for cross-account access with multiple accounts configured in `~/.aws/config`?  If I manually setup env vars with STS creds to an ECR account, `docker-credentials-ecr-login` seems to work, but `docker pull` does not:

```sh
$ echo $REPO_URL | docker-credential-ecr-login get
2017-04-05T20:21:40Z [ERROR] Error retrieving credentials: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
credentials not found in native keychain
```
```sh
$ `aws_become.sh ecr-dev-account`    # STS to correct account and export env vars
$ echo $REPO_URL | docker-credential-ecr-login get
{"ServerURL":"","Username":"AWS","Secret":"..."}
$ docker pull $REPO_URL/my_containers/test:latest
Pulling repository $REPO_URL/my_containers/test:latest
unauthorized: authentication required
```

**Comment by samuelkarp** [comment]
@rvandegrift If you have multiple accounts configured in `~/.aws/credentials` (with credentials) you can do `AWS_PROFILE=myprofile docker pull`.  If you have multiple accounts configured in `~/.aws/config` with a `role_arn` and `source_profile` set up, you can do `AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=myprofile docker pull`.

Please let me know if you have any further questions.

**Comment by rvandegrift** [comment]
Oh I didn't know about `AWS_SDK_LOAD_CONFIG` - works well, thanks!

**Comment by resurtm** [comment]
@rvandegrift, @samuelkarp, is there any way to make it permanent in ECR helper config? Thanks!

**Comment by ronaldegmar** [comment]
`AWS_SDK_LOAD_CONFIG=true AWS_PROFILE=myprofile docker pull` works for me, but I cannot make it work with nomad. I have inserted those environment variables in nomad systemd unit file, docker systemd unit file and nothing. It seems that those cannot be set up permanent in the ECR helper config too.
