### ISSUE TITLE
Error "duplicate method GetInitialToken"

### ISSUE THREAD

**Issue by g-portugues** [awslabs/amazon-ecr-credential-helper#346]
After the last PR submitted, the error "duplicate method GetInitialToken" started to occur.

Command: `go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login`

**Comment by g-portugues** [comment]
![image](https://user-images.githubusercontent.com/29684340/177627437-0e2ff997-0ac2-4685-9e39-1458979a9103.png)

**Comment by travispeloton** [comment]
Seen in our Jenkins pipeline:

```
11:20:32  + go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
11:20:33  # github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/aws/aws-sdk-go-v2/aws
11:20:33  /root/go/src/github.com/awslabs/amazon-ecr-credential-helper/ecr-login/vendor/github.com/aws/aws-sdk-go-v2/aws/retryer.go:81:2: duplicate method GetInitialToken
```

**Comment by g-portugues** [comment]
1.13

**Comment by travispeloton** [comment]
We were able to resolve our issue by updating our container to a version that installed Go 1.18.x:

Old:
```
image: gradle:7.1.1-jdk11
...
                    sh "apt-get update"
                    sh "apt-get install -y golang-go"
                    sh "go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login"
```

New:
```
image: gradle:7-jdk11
...
                    sh "apt-get update"
                    sh "apt-get install -y golang-go"
                    sh "go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest"
```

**Comment by g-portugues** [comment]
> We were able to resolve our issue by updating our container to a version that installed Go 1.18.x:
> 
> Old:
> 
> ```
> image: gradle:7.1.1-jdk11
> ...
> sh "go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login"
> ```
> 
> New (`go install` with `@latest`, which installs the most recent release):
> 
> ```
> image: gradle:7-jdk11
> ...
> sh "go install github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login@latest"
> ```


success! thanks!
