### ISSUE TITLE
Integration with Docker Remote API

### ISSUE THREAD

**Issue by Spareo** [awslabs/amazon-ecr-credential-helper#37]
I am having a very hard time being able to access ECR using the docker Remote API. I have setup the credential helper locally and it works just fine  when I use docker commands in the local CLI. However, it doesn't seem to do anything when I make remote API calls.

Is there any information on how we are supposed to access ECR using the docker remote API?

**Comment by samuelkarp** [comment]
The Docker Remote API doesn't use the credential helpers; those are only invoked by the Docker CLI.  There's a good example of interacting with the Remote API to push/pull with ECR in the ECS CLI (see [here](https://github.com/aws/amazon-ecs-cli/blob/744a682035833d2415abee4cbd255865bae539ce/ecs-cli/modules/cli/image/image_app.go#L192-L208)).

**Comment by Spareo** [comment]
So I have come to that same conclusion. I looked over the code you linked and in particular the dockerclient. I see that the interface it implements only does push/pull/tag.

My main goal was to push a .tar.gz archive to S3 and use docker build on an EC2 instance to create an image from the dockerfile and contents of the archive and push it to ECR. I need to do this remotely which is the main issue. 

The code you linked me seems like it would handle the push but not the build. Is there anything out there that could accomplish the image build and push to ECR functionality I need?

**Comment by samuelkarp** [comment]
@Spareo Have you looked at [AWS CodeBuild](https://aws.amazon.com/codebuild/)?  They have an [example](http://docs.aws.amazon.com/codebuild/latest/userguide/sample-docker.html) of building a Docker image and pushing it to ECR.

**Comment by Spareo** [comment]
Yes Codebuild was what I wanted to use initially but they don't have windows codebuild images yet which I need to build a windows docker image.

**Comment by Spareo** [comment]
@samuelkarp Can you tell me if I have the ECS, docker optimized windows AMI with the ecs agent running in an EC2 instance, does that still have to do a docker login to push/pull from ECR? Would that help me at all in my situation?

**Comment by samuelkarp** [comment]
The "Microsoft Windows Server 2016 Base with Containers" AMI does still need to do a `docker login`, use the credential helper, or use the ECS agent to pull from ECR.

> The code you linked me seems like it would handle the push but not the build. Is there anything out there that could accomplish the image build and push to ECR functionality I need?

You can build images through the Docker Remote API as well.  I've had good experiences using [go-dockerclient](https://godoc.org/github.com/fsouza/go-dockerclient#Client.BuildImage) to interact with the Remote API.

**Comment by Spareo** [comment]
@samuelkarp  Thanks for the quick response. In regards to your second comment about docker build, are you saying I can use go-dockerclient to build docker images that pull a base image from ECR? Thats where everything is falling apart for me right now. 

Even with passing in credentials and the correct headers and everything I always get an error that says "no basic auth credentials" when the image I want to build has a FROM statement that pulls from ECR.

**Comment by samuelkarp** [comment]
@Spareo Are you specifying `AuthConfigs` in [`BuildImageOptions`](https://godoc.org/github.com/fsouza/go-dockerclient#BuildImageOptions)?

**Comment by Spareo** [comment]
Yes I tried passing in in the auth information several times using different credentials and it acted as though it was just ignoring it. I was able to use the /auth end point which would return a "Login Succeeded" response but it would never return an Identity token. When I used the same credentials with the build endpoint, it would still fail.

**Comment by bklau** [comment]
@Spareo  Can you do an image pull from ECR using docker Remote API?. Just curious.

**Comment by dduquesne** [comment]
@bklau No. I spent the last 3 days trying to make it work. There is no way. I give up now and i am going to create my own private registry in my facilities.
