### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by astryia** [awslabs/amazon-ecr-credential-helper#38]
Since we have Docker for Windows, is possible to build this helper on Windows platform?

**Comment by samuelkarp** [comment]
I haven't tested it extensively, but it worked last time I tried.  If you want to cross-compile from another operating system, you can run `TARGET_GOOS=windows make`.  Are you having issues using the credential helper on Windows?

**Comment by astryia** [comment]
Since I'm not familiar with Go it was difficult for me to build the helper, and described approach with make doesn't work. But after I've built helper directly with
`go build -o bin/docker-credential-ecr-login.exe ecr-login\cmd\main.go`
everything became perfect.

Credential helper works on Windows as expected.

Thank you.

**Comment by samuelkarp** [comment]
I'm glad you were able to build it and get it running!  If you're interested in helping to make the README more clear for people using Windows, we'd be happy to have the contribution.
