### ISSUE TITLE
Problem authenticating with profiles

### ISSUE THREAD

**Issue by miguelgm** [awslabs/amazon-ecr-credential-helper#40]
I am sorry to open another ticket like this, I saw other tickets like this one already closed.

When trying to use a profile configured in .aws/credentials, docker pull fails. This is the .ecr/log content:

> 2017-06-09T12:20:54Z [DEBUG] Could not fetch credentials for cache prefix: NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2017-06-09T12:20:54Z [DEBUG] Disabling cache
2017-06-09T12:20:54Z [DEBUG] Retrieving credentials for XXXXXXXXXXX in eu-west-1 (XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com)
2017-06-09T12:20:54Z [DEBUG] Calling ECR.GetAuthorizationToken for XXXXXXXXXXXXX
2017-06-09T12:21:14Z [ERROR] Error retrieving credentials: NoCredentialProviders: no valid providers in chain. Deprecated. 
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors

If I change the any of the profiles to default, it works.

I have already tried your suggestion of the other tickets about the environment variables, but it is still not working for me :(

$ docker --version
Docker version 17.03.1-ce, build c6d412e
$ cat /etc/issue
Ubuntu 14.04.5 LTS
I have built the docker-credential-ecr-login today using `make docker`

**Comment by samuelkarp** [comment]
Can you let me know exactly what you tried?  Which environment variables you set and how you invoked `docker pull`?  You can redact anything that you need to (profile names, image names, etc), but I'd like to see exactly how you're invoking it.

**Comment by miguelgm** [comment]
This is the full ouput of what I did

> $ env |grep AWS
> $ export AWS_PROFILE=profile1
> $ env |grep AWS
> AWS_PROFILE=profile1
> $ docker pull XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/nexus:arch-1520-to-2.0-SNAPSHOT
> Pulling repository XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/nexus
> unauthorized: authentication required
> $ export AWS_DEFAULT_PROFILE=profile1
> $ env |grep AWS
> AWS_PROFILE=profile1
> AWS_DEFAULT_PROFILE=profile1
> $ docker pull XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/nexus:arch-1520-to-2.0-SNAPSHOT
> Pulling repository XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/nexus
> unauthorized: authentication required
> $ cat .aws/credentials 
> [profile1]
> aws_region = eu-west-1
> aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> aws_access_key_id = XXXXXXXXXXXXXXX
> [profile2]
> aws_region = eu-west-1
> aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> aws_access_key_id = XXXXXXXXXXXXXXX

If I change the profile1 to default in the credentials file, it works without any env variable.

**Comment by samuelkarp** [comment]
There should be a log file in `~/.ecr/log` that may have a bit more information as to what's going on.  Can you check and see if you see any `ERROR`s or `WARN`ings?

(this is a bit of a long shot) Can you also try `AWS_PROFILE=profile1 docker pull XXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/nexus:arch-1520-to-2.0-SNAPSHOT` rather than relying on the environment variable being exported?

**Comment by cmcconnell1** [comment]
Hello, I've started having issues with the credential helper some time ago.
I'm not sure exactly when as I've been on other projects.  
I too tried a fresh build of the cred util and updated in /usr/local/bin to no avail.
In my case, I can't do a docker push which used to work as configured.  But the caveat is that I've updated many utilities, docker awscli, etc.

```
docker push 123456789.dkr.ecr.us-west-1.amazonaws.com/foo/redis:latest
The push refers to a repository [123456789.dkr.ecr.us-west-1.amazonaws.com/foo/redis]
d839f120ccc6: Preparing
3deabc5be693: Preparing
e2a7974c963a: Preparing
dfc674f407ff: Preparing
875f50000be3: Preparing
2604e558d0d3: Waiting
f0a74fc06c52: Waiting
5bef08742407: Waiting
no basic auth credentials

$ aws --version
aws-cli/1.11.150 Python/2.7.10 Darwin/15.6.0 botocore/1.7.8
$ docker --version
Docker version 17.06.2-ce, build cec0b72

cat config.json
{
	"credsStore": "ecr-login"
}
```

Note that If I switch back my config.json and go with ecr auth, all works as expected:

```
COMMAND=$(aws ecr get-login --region us-west-1 --no-include-email)
$ echo $(eval $COMMAND)
Login Succeeded

$ docker push 123456789.dkr.ecr.us-west-1.amazonaws.com/foo/redis:latest
The push refers to a repository [076613928512.dkr.ecr.us-west-1.amazonaws.com/foo/redis]
d839f120ccc6: Layer already exists
3deabc5be693: Layer already exists
e2a7974c963a: Layer already exists
dfc674f407ff: Layer already exists
875f50000be3: Layer already exists
2604e558d0d3: Layer already exists
f0a74fc06c52: Layer already exists
5bef08742407: Layer already exists
latest: digest: sha256:0398018597d378d021fc902d89b66e9e5c6798274e68e37326e216e871016dc1 size: 1984
```

RE: logs
I don't see any errors at all or even a new file in ~/.ecr/log only old files from back in july.
Hope this helps?

Thanks

**Comment by samuelkarp** [comment]
@cmcconnell1 
>  I don't see any errors at all or even a new file in ~/.ecr/log only old files from back in july.

It sounds like the credential helper isn't being invoked.  You mentioned that you put the binary in `/usr/local/bin`; is that on your `PATH`?  Can you invoke `docker-credential-ecr-login` without specifying its full location?

**Comment by miguelgm** [comment]
Finally worked:
```
AWS_PROFILE=profile1 docker pull xxxxxxxxxxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/nexus:arch-1547-to-2.14.1-SNAPSHOT
```

There has been a lot of changes in my setup since I opened the ticket so, I don't really know what are the differences between now and then :(

This is my current config:
```
$ cat .docker/config.json 
{
        "credsStore": "ecr-login"
}

$ cat .aws/credentials 
[profile1]
aws_region = eu-west-1
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
aws_access_key_id = XXXXXXXXXXXXXXXX
[profile2]
aws_region = eu-west-1
aws_secret_access_key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
aws_access_key_id = XXXXXXXXXXXXXXXX

$ cat .aws/config 
[profile profile1]
region = eu-west-1
output = text
[profile profile2]
region = eu-west-1
output = text
```
Still, would be nice to have a way to configure specific AWS profile in the .docker/config.json the same way you can do with specific registries.

**Comment by samuelkarp** [comment]
@miguelgm Thanks for the update.  I'm glad it's working, but I also don't understand why it wasn't working before and is working now.  I'm going to close this issue; if anyone else has problems please open a new issue.

> Still, would be nice to have a way to configure specific AWS profile in the .docker/config.json the same way you can do with specific registries.

That sounds like a neat idea.  I'm not sure how that would be possible today; `~/.docker/config.json` really only provides the single `credsStore` field for configuration and doesn't pass along anything else.  The only things I can think of here are a separate configuration file for the credential helper inside `~/.ecr` or maybe doing something like creating a symlink to the credential helper with the profile name embedded in it and then parsing `os.Args[0]`?

**Comment by beemi** [comment]
export AWS_PROFILE=profileName
AWS_PROFILE=profileName docker-compose up --build

Works for me
