### ISSUE TITLE
credHelpers and docker-compose

### ISSUE THREAD

**Issue by d3v1an7** [awslabs/amazon-ecr-credential-helper#41]
Hi there, big fan of #39 as this is much more polite way of handling docker auth :)
Unfortunately, it doesn't seem to work in combination with docker-compose.

**Currently working config**
```
{
  "auths" : {
    "[aws_account_id].dkr.ecr.[region].amazonaws.com" : {}
  },
  "credsStore" : "ecr-login"
}
```

**Not working**
```
{
  "credHelpers" : {
    "[aws_account_id].dkr.ecr.[region].amazonaws.com" : "ecr-login"
  }
}
```

I also tried the following (as we `FROM` the same repo quite a bit) without success.
```
{
  "credHelpers" : {
    "[aws_account_id].dkr.ecr.[region].amazonaws.com" : "ecr-login"
  },
  "auths" : {
    "[aws_account_id].dkr.ecr.[region].amazonaws.com" : {}
  }
}
```

**Error**
```
$ docker-compose pull
latest: Pulling from library/mysql
Digest: sha256:d178dffba8d81afedc251498e227607934636e06228ac63d58b72f9e9ec271a6
Status: Image is up to date for mysql:latest
Pulling [imagename] ([aws_account_id].dkr.ecr.[region].amazonaws.com/[path]:[tag])...
Pulling repository [aws_account_id].dkr.ecr.[region].amazonaws.com/[path]
ERROR: unauthorized: authentication required
```

**Comment by danielcompton** [comment]
This is an issue with docker-compose, I hit the same issue: https://github.com/docker/compose/issues/4948. The docs should probably be updated to point this out, as it's not obvious that this won't work for docker-compose.

**Comment by d3v1an7** [comment]
Thanks @danielcompton.

FYI, I've been able to get `credsStore` to work fine, with the addition of `auths` (see working example in OP). That was thanks to comments [here](https://github.com/awslabs/amazon-ecr-credential-helper/issues/16#issuecomment-256727200) and [here](https://github.com/awslabs/amazon-ecr-credential-helper/issues/9#issuecomment-241184224).

It's `credHelpers` that I'm bringing up in this ticket, but I suspect you're correct in that this may be more of a docker-compose issue than an ecr-helper one...

**Comment by samuelkarp** [comment]
@d3v1an7 Yes, as @danielcompton mentioned this is an issue with docker-compose instead of the credential helper.  I'm going to close this in favor of https://github.com/docker/compose/issues/4948, but let me know if you run into further issues once that one gets fixed.
