### ISSUE TITLE
Access images from another AWS account

### ISSUE THREAD

**Issue by astryia** [awslabs/amazon-ecr-credential-helper#42]
I want to pull/push images from another AWS account repository.
As described there https://aws.amazon.com/premiumsupport/knowledge-center/secondary-account-access-ecr/?tag=vig-20, I need to pass registry-ids

`aws ecr get-login –-registry-ids <account_ID_of_repository>`

My question is how to do this with ecr-credential-helper?

**Comment by samuelkarp** [comment]
@astryia As long as you have the appropriate permissions on the repository you're attempting to access, the credential helper will handle this transparently for you.  Are you having issues using it?

**Comment by astryia** [comment]
I thought that it's necessary to pass registry-id in some way. It's great if credential helper handles this transparently.
I'm going to perform test setup, I'll back to you in case of an issue.
Thank you very mach.
