### ISSUE TITLE
Support c2s AWS environments

### ISSUE THREAD

**Issue by jrsherry** [awslabs/amazon-ecr-credential-helper#433]
The regex for determining if the ECR URI is valid needs to be updated to support c2s AWS environments.

**Comment by jrsherry** [comment]
Here's a PR that picks up the pattern used in mainline kubernetes: https://github.com/awslabs/amazon-ecr-credential-helper/pull/434/files

**Comment by thecodebeneath** [comment]
Our project could benefit from this PR solution c2s environments. Upvote.

**Comment by speedythesnailnpg** [comment]
> Here's a PR that picks up the pattern used in mainline kubernetes: https://github.com/awslabs/amazon-ecr-credential-helper/pull/434/files

It would be great to have this PR looked at!

**Comment by austinvazquez** [comment]
Issue resolved by #434 and will be included in 0.8.0 release.
