### ISSUE TITLE
no basic auth credentials yet AWS CLI has access

### ISSUE THREAD

**Issue by guyisra** [awslabs/amazon-ecr-credential-helper#49]
I am using Docker v17 and for some reason when trying to push to ECR I get no basic auth credentials.

This doesn't happen if I manually login with `aws ecr get-login ...`

the policy is configured correctly, I can run other AWS commands.
It gives the same response with either a profile with the proper policy or with the access key and secret explicitly set..

**Comment by danielcompton** [comment]
I just updated to the current Docker for Mac (17.06-ce I think?) and got the same error:

```console
$ docker-compose up -d
Creating network "service_default" with the default driver
Pulling <redacted>
ERROR: Get <redacted>: no basic auth credentials
```

**Comment by samuelkarp** [comment]
@guyisra Can you provide the logs in `~/.ecr/log`?  Also, can you describe what exact commands you're using? (`docker push`, `docker pull`, `docker build`, etc?)

@danielcompton I think you already know this, but docker-compose is different from the normal Docker CLI and may not support all of the same features.  Can you also provide the logs in `~/.ecr/log` to see if docker-composes is even requesting credentials to the right registries?

**Comment by mskutin** [comment]
Hit into this too.

`docker pull` : 
```json
{
    "changed": false,
    "failed": true,
    "msg": "Error pulling image ID.dkr.ecr.REGION.amazonaws.com/IMAGE:latest - 500 Server Error: Internal Server Error (\"Get https://ID.dkr.ecr.REGION.amazonaws.com/IMAGE/manifests/latest: no basic auth credentials\")"
}
```
`~/.ecr/log/`
```bash
2017-07-13T11:32:21Z [DEBUG] Listing credentials
2017-07-13T11:40:36Z [DEBUG] Retrieving credentials for ID in REGION (ID.dkr.ecr.REGION.amazonaws.com)
2017-07-13T11:40:36Z [DEBUG] Checking file cache for ID
2017-07-13T11:40:36Z [DEBUG] Calling ECR.GetAuthorizationToken for ID
2017-07-13T11:40:36Z [ERROR] Error retrieving credentials: InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/

content-length:32
content-type:application/x-amz-json-1.1
host:ecr.REGION.amazonaws.com
x-amz-date:20170713T114036Z
x-amz-target:AmazonEC2ContainerRegistry_V20150921.GetAuthorizationToken

content-length;content-type;host;x-amz-date;x-amz-target
3d'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20170713T114036Z
20170713/REGION/ecr/aws4_request
18928a6554f61232918f795f2f849a972841bbd11175871635d2a8e9e169fbca35'

	status code: 400, request id: 164ebc6c-64c0-11e7-a910-67cd82798c70
```
`docker info`:
```
Server Version: 17.06.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-1020-aws
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858GiB
```

**Comment by samuelkarp** [comment]
@mskutin Thanks for providing the log; that's very helpful.  Can you let me know what region this was for so I can investigate further?

**Comment by mskutin** [comment]
@samuelkarp **ap-southeast-1a**, but I've randomly changed x-request-id :)

**Comment by samuelkarp** [comment]
@mskutin Can you provide the correct request ID?  I'd like to correlate what the logs you provided show with what I can find out from our side.

**Comment by igostavro** [comment]
not sure if this helps, but everything started working for me after i moved docker-credential-ecr-login into /usr/local/bin, its bizarre, i had its path stored in the PATH environment variable.

**Comment by corymacd** [comment]
Had the same issue. Using @igostavro's workaround of moving the binary to /usr/local/bin was the only way that I was able to push, even though it had been very much in the PATH.

**Comment by samuelkarp** [comment]
@igostavro @corymacd Your issues look to be unrelated to what @mskutin reported. If the Docker CLI had trouble invoking because of something involving `PATH` you wouldn't see the same errors that @mskutin saw.

I'm closing this issue for now because we haven't heard back from @mskutin and cannot investigate further without that information.

**Comment by yohei1126** [comment]
Hi, I see the same issue.
I tried to push docker image to ECR then I got this error.

```
docker push xx.dkr.ecr.ap-northeast-1.amazonaws.com/kafka:latest
The push refers to a repository [xx.dkr.ecr.ap-northeast-1.amazonaws.com/kafka]
d3a49746dc78: Preparing 
86732a3c9fa2: Preparing 
8eff05291997: Preparing 
4a4be3bbe7b8: Preparing 
1d63b624ee12: Preparing 
64a72f460067: Preparing 
65f2d0254776: Preparing 
e315e40a6a4f: Preparing 
no basic auth credentials
```

I am using docker 17.06.2-ce.

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: moby
ID: SR2O:ICK2:6GBS:LBCT:FMEP:BZPA:Z7OG:6XAP:DMHZ:55KX:FHDN:UJHF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-09-14T23:22:42.225546039Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by samuelkarp** [comment]
@yohei1126 Please open a new issue and provide the logs in ~/.ecr/log? Also, can you describe what exact commands you're using? (docker push, docker pull, docker build, etc?)

**Comment by yohei1126** [comment]
Opened #66. Thanks.

**Comment by tripleee** [comment]
If the Docker daemon started before you updated your `PATH` then it does not have access to the [AWS ECR Docker helper](https://github.com/awslabs/amazon-ecr-credential-helper). Try quitting and restarting Docker with the `PATH` set to include the directory which contains the helper binary.

(To update your system-wide `PATH` without rebooting on MacOS, run `launchctl setenv PATH "$PATH"` in a place where you have the `PATH` set up correctly.)
