### ISSUE TITLE
Possible refactor not using /src/github.com path?

### ISSUE THREAD

**Issue by guyisra** [awslabs/amazon-ecr-credential-helper#50]
Is it possible to refactor this so it won't need a very explicit and hard-coded path?

**Comment by samuelkarp** [comment]
Go requires packages to be in this directory structure (named by the import path); see [GOPATH](https://github.com/golang/go/wiki/GOPATH) for more information.

However, we could do something [like this](https://github.com/moby/moby/blob/ea2e4d73c4c753cdc99966e4dfe35143e79564ce/hack/make.sh#L95-L99) where a temporary GOPATH is made and symlinked by the Makefile.  On the other hand, we already have a mechanism that doesn't require a specific directory structure via `make docker`.

**Comment by guyisra** [comment]
thanks, didn't realize that go works that way
