### ISSUE TITLE
amazon-ecr-credential-helper seems not to work with stack deploy

### ISSUE THREAD

**Issue by ieugen** [awslabs/amazon-ecr-credential-helper#559]
Hi, 

For some reason `amazon-ecr-credential-helper` does not seem to work with stack deploy ?

I have configured this plugin on an EC2 single node swarm cluster. 
I added an IAM role to the server and configured `amazon-ecr-credential-helper` 

I can pull images on the node having this as my config:
```json
cat ~/.docker/config.json 
{
  "credsStore": "ecr-login"
}
```
When I try to deploy (via remote docker context)
```shell
docker --context prod stack deploy --prune --with-registry-auth --compose-file stack-generated.prod.yml prod
````
I get 
```
Updating service prod_api (id: m5532j1sinw4jzekmgtmddjh4)
image REDACTED.dkr.ecr.us-east-1.amazonaws.com/api:main-latest could not be accessed on a registry to record
its digest. Each node will access REDACTED.dkr.ecr.us-east-1.amazonaws.com/api:main-latest independently,
possibly leading to different nodes running different versions of the image.
```

**Comment by ieugen** [comment]
I think I solved this. 

I have to be authenticated on the node I am running the deployment from and this will work. 

I am running form my laptop, onto a remote docker swarm (remote docker context). 
Once I authenticated locally, this worked.

**Comment by chrisbecke** [comment]
This doesn't work because the --with-registry-auth caches the credentials in the swarm RAFT log, and they only last for 12h.

If, after 12h, your swarm migrates tasks to a new node that does not have the image, the worker will try using those stale credentials and fail to create a new container.

**Comment by untoldone** [comment]
I believe this to still be an issue today (the cached creds expire and deploying doesn't seem to work unless this is setup locally)? At a minimum this is not documented adequately
