### ISSUE TITLE
How to control  ecr-login log output

### ISSUE THREAD

**Issue by bklau** [awslabs/amazon-ecr-credential-helper#64]
This is just a question:
I noticed that there are a set of  ECR-login logs located at ~/.erc/log/.
Q: Are these being rotated?. If not it, it will grow graduately and depletes disk space.
Anyway to configure logging? Thx.

**Comment by samuelkarp** [comment]
The log configuration is here: https://github.com/awslabs/amazon-ecr-credential-helper/blob/e63ef99f0995dda1bbbf10b2fdb4f55d458d6d52/ecr-login/config/seelog.go#L46-L57

Rotation is configured, but rotation will only happen while the credential helper is actually running (when a `docker push` or `docker pull` is initiated).

We would be open to a pull request making logging more configurable.

**Comment by bklau** [comment]
@samuelkarp  Is there anyway to configure logging only errors in the log?. The reason is calls to the credential helper is getting slower as the logs gets longer i noticed.
I prefer not to modify the amazon-ecr-credential-helper/ecr-login/config/seelog.go due to Licensing directive from our Legal. May some non-golang Json or  config file?

**Comment by samuelkarp** [comment]
The 0.2.0 release has moved to logrus instead of seelog.  Logs are now written to `~/.ecr/log/ecr-login.log` and can be rotated using `logrotate(8)`.

**Comment by Ianwww** [comment]
I don't notice any logs on my mac for ecr, has the location been changed? The only file in ~/.ecr/ is cache.json.  I am trying to debug why another app isn't using ecr and still attempting to use the osxkeychain. @samuelkarp

**Comment by samuelkarp** [comment]
@Ianwww The logs are still in `~/.ecr/log`, but if your application is using osxkeychain I wouldn't expect to see logs (ecr-login is likely not being invoked).
