### ISSUE TITLE
Docker for aws

### ISSUE THREAD

**Issue by sabareeshkkanan** [awslabs/amazon-ecr-credential-helper#71]
Lets say i deployed my swarm using https://docs.docker.com/docker-for-aws/ 
and manually setup the auth on the machines. Now if i update the cloud formation property to increase number of nodes does it automatically configure setup the credential helper or do i have to set this manually ?

**Comment by samuelkarp** [comment]
For help with Docker for AWS, you should reach out to the Docker project on https://github.com/docker/for-aws.

I don't know if Docker for AWS supports using credential helpers, but https://github.com/moby/moby/issues/30982 and https://github.com/moby/moby/issues/31063 imply that it does not.

> and manually setup the auth on the machines

If you manually set something up on an instance and then scale your autoscaling group without encoding the additional setup into the autoscaling group launch configuration, that manual setup will not be transferred over to the new instances.  See [the documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) for how to run commands at instance boot that can be encoded into your launch configuration.
