### ISSUE TITLE
Version numbers and releases

### ISSUE THREAD

**Issue by lox** [awslabs/amazon-ecr-credential-helper#74]
I've been maintaining a fork at https://github.com/lox/amazon-ecr-credential-helper and publishing releases. Lots of people are using them, and it's causing confusion. My hope was that it would prompt some action around issue #15, which has now been open for a year. 

If the issue is one of time and resources, perhaps I could be added as a maintainer and could lead an effort to put out a release and keep a semver changelog? I think by now I would have spent as much time on that as I have in hassling you folks with issues, and I'd much rather spend my time that way. 

If it's not time and resources, perhaps you could provide a concrete statement of why no releases are being made and chime in on https://github.com/Homebrew/homebrew-core/pull/18914?

**Comment by samuelkarp** [comment]
Closing in favor of https://github.com/awslabs/amazon-ecr-credential-helper/issues/80, which is tracking the work necessary for this to happen.
