### ISSUE TITLE
build on Windows creates an ELF 64 LSB executable - is this correct? 

### ISSUE THREAD

**Issue by sbutt** [awslabs/amazon-ecr-credential-helper#75]
Hi, I've ran "make docker" on a Windows 10 machine, which has docker installed and it's produced a file docker-credential-ecr-login however this file is not able to execute on Windows. Am I barking up the wrong tree here? I want to be able to use ecr cred helper on Windows but I'm not sure what to do with the binary that's been created. I tried renaming it and adding .EXE on the end, but that refuses to run also. 
```

$ ./docker-credential-ecr-login.exe
bash: ./docker-credential-ecr-login.exe: cannot execute binary file: Exec format error

$ file docker-credential-ecr-login.exe
docker-credential-ecr-login.exe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```
Apologies if I'm doing something stupid. :)

Steve

**Comment by samuelkarp** [comment]
`make docker` will default to producing a Linux executable, since it runs in a Linux container.  You can cross-compile and produce a Windows executable by running `make TARGET_GOOS=windows docker` and then renaming the resulting executable and adding `.exe`.

**Comment by sbutt** [comment]
Many thanks, that worked.
