### ISSUE TITLE
Support for Multiple AWS Profiles

### ISSUE THREAD

**Issue by etsuo** [awslabs/amazon-ecr-credential-helper#77]
Currently, as far as I can tell, `docker-credential-ecr-login` only allows you to use the `default` aws credentials profile. It would be VERY helpful to allow multiple profiles for scenarios where a single CI/CD server is responsible for pushing images to different regions depending on whether it's a production build or a develop build (etc.). This also helps for those of us who support multiple customers, each with their own AWS accounts.

**Comment by samuelkarp** [comment]
It works for me when I do `AWS_PROFILE=myprofile docker push`.  Are you having problems with that?

**Comment by etsuo** [comment]
@samuelkarp sorry, it hadn't occurred to me to do that, though it should have. I'm sure that'll work for me. Thanks for the quick reply!!

**Comment by etsuo** [comment]
Actually, this does not seem to be working... I'm getting: `no basic auth credentials` when I run: `AWS_PROFILE={redacted} docker push {redacted}.dkr.ecr.{redacted}.amazonaws.com/{redacted}:latest`

Any thoughts as to why that might be? I have a profile setup, and I can use it with the `aws` cli...

**Comment by etsuo** [comment]
ps. As a sanity check, I ran `AWS_PROFILE=myprofile aws iam getuser` while logged in as the user, and it worked. I also dropped a trace in my CI script that outputs `whoami` and it's the right linux user for the `aws` and `docker` setup... and it's all working with the default aws credentials.

**Comment by etsuo** [comment]
ok, found the problem. It was a security issue. Turns out `docker-credential-ecr-login` requires the AWS user to have `ecr:GetAuthorizationToken` on resource `*`. I vaguely remember running into this when I setup my last ECR / docker config. After adding the appropriate policy, `docker push` with `AWS_PROFILE=myprofile` worked fine. 

If anyone else runs into this in the future, check your ~/.ecr/log directory for specific error messages.

**Comment by ybychenok** [comment]
It would be great to have this in main README.md.

**Comment by samuelkarp** [comment]
@ybychenok Would you be interested in sending a pull request to update the README.md?

**Comment by ybychenok** [comment]
Ok, I'll try.

**Comment by tdaniely** [comment]
FFU
install docker-credential-ecr-login
create an excutable script in your path i.e ~/.local/bin/docker-credential-ecr-auto
```bash
#!/usr/bin/env bash
if [ "get" == "$1" ]; then
    read REGISTRY < /dev/stdin
    echo $REGISTRY | AWS_PROFILE=$REGISTRY docker-credential-ecr-login get
fi
```
put your registries in docker config
```json
{
	"credHelpers": {
		"888888888888.dkr.ecr.us-east-1.amazonaws.com": "ecr-auto"
		"999999999999.dkr.ecr.us-east-2.amazonaws.com": "ecr-auto"
	},
	...
}
```
add profile for each registry in ~/.aws/config
```ini
[profile 888888888888.dkr.ecr.us-east-1.amazonaws.com]
region = us-east-1
source_profile = actual profile
...
[profile 999999999999.dkr.ecr.us-east-2.amazonaws.com]
region = us-east-2
source_profile = actual profile
...
```

**Comment by Shubhranshu153** [comment]
Reopening the ticket as a feature request.

**Comment by mikeroll** [comment]
Meanwhile, my version of @tdaniely's script:
```
#!/bin/zsh
set -euo pipefail

typeset -A registries=(
  "<account>.dkr.ecr.<region>.amazonaws.com" "<profile>"
)

payload="$(tee)"

case "$1" in
    get | erase)
        server_url="${payload}"
        ;;
    store)
        server_url="$(jq '.ServerURL' <<< "${payload}")"
        ;;
esac

if [[ -n "${server_url}" ]]; then
    export AWS_PROFILE="${registries[$server_url]}" 
fi

echo "${payload}" | docker-credential-ecr-login "$@"
```
