### ISSUE TITLE
Binary missing after make docker on CIS Amazon Linux

### ISSUE THREAD

**Issue by shadycuz** [awslabs/amazon-ecr-credential-helper#79]
```
[ec2-user@ip-10-25-16-103 amazon-ecr-credential-helper]$ sudo make docker
docker run --rm \
-e TARGET_GOOS= \
-e TARGET_GOARCH= \
-v /home/ec2-user/amazon-ecr-credential-helper/bin:/go/src/github.com/awslabs/amazon-ecr-credential-helper/bin \
sha256:0b4e6e7e6983ed54dfb9da8223727d334e0c9238e8283852470ef2f4248aae15
. ./scripts/shared_env && ./scripts/build_binary.sh ./bin/local
Built ecr-login
```

```
[root@ip-10-25-16-103 ~]# ls /bin/local
ls: cannot access /bin/local: No such file or directory
```

**Comment by shadycuz** [comment]
I found it in the repo? Is this normal? 
```
[ec2-user@ip-10-25-16-103 amazon-ecr-credential-helper]$ ls bin/local/
docker-credential-ecr-login
```

**Comment by samuelkarp** [comment]
Yes, it builds into `./bin/local`, not `/bin/local`.

**Comment by shadycuz** [comment]
@samuelkarp Documentatiom from the above aws link is bad.

> First, build a binary for your client machine. Although you can do it with your own Go environment, we also provide a way to build it inside a Docker container without installing Go by yourself. To build by container, just type make docker on the root directory of the repository. It will run a container FROM go image and build the binary on the mounted volume. After that, you can see it at /bin/local/docker-credential-ecr-login.

**Comment by samuelkarp** [comment]
@shadycuz Can you link to where you see that?  I don't see a link in your previous correspondence.

**Comment by shadycuz** [comment]
@samuelkarp my bad =) 

https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/

**Comment by samuelkarp** [comment]
@shadycuz Thanks!  I can follow up with the right person to get that fixed.

**Comment by samuelkarp** [comment]
@shadycuz That blog post should be fixed now.
