### ISSUE TITLE
Release new version/tag due to breaking change of aws-sdk `v1.23.0`

### ISSUE THREAD

**Issue by seternate** [awslabs/amazon-ecr-credential-helper#797]
Hello,

recently we ran into a problem in Tekton, where we get a `401 Not Authorized` when trying to access our private ECR. 
I had a look into it and found that a version mismatch between 2 dependencies inside of Tekton causes this behaviour. More or less it comes down to the aws-sdk module and its dependend modules and its breaking change with `v1.23.0` (see https://github.com/aws/aws-sdk-go-v2/issues/2370). 

Since your latest release/tag of `v0.7.1` includes the aws-sdk with the version `v1.18.x` (which is `<v1.23.0`) this leads to a buggy behaviour if another dependency is using aws-sdk with `>v1.23.0`. For more details of the error we encountered see the Tekton issue https://github.com/tektoncd/pipeline/issues/7698.

The package is up-to-date on the main branch, so I wanted to ask if you could release a new version? This would fix this problem for up-stream projects using multiple dependencies.

**Comment by austinvazquez** [comment]
Hi @seternate, great timing. I am putting together the resources for the 0.8.0 release.

I don't have an accurate timeline at the moment but have opened #798 with the required version and changelog updates. I will try to post some updates there based on the progress.
