### ISSUE TITLE
Tagged releases and binary artifacts

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/amazon-ecr-credential-helper#80]
Hey all,

There have been a [few](https://github.com/awslabs/amazon-ecr-credential-helper/issues/15) [different](https://github.com/awslabs/amazon-ecr-credential-helper/issues/33) [issues](https://github.com/awslabs/amazon-ecr-credential-helper/issues/74) asking questions about publishing tagged releases and binaries.  I wanted to provide a list of what things need to occur before those can happen just to give a bit more context.  These are all things that we do for the other binaries released by ECS including the ECS agent and ECS CLI.

For tagged releases, we need to do the following:

* [x] Pick a versioning scheme and assign a first version.  Right now there is no version.
* [x] Expose a way to interactively query the version of the installed binary.  This is probably a `-v` or `--version` flag.  This can be contributed if anyone is looking to do so.
* [x] Override the default user-agent string used by the AWS SDK to include the name of the program and the version number.  We want this for tracking the usage of the credential helper vs. the AWS CLI or interacting with the API and to track different versions of the credential helper.  This can be contributed if anyone is looking to do so.
* [x] Determine release criteria for when a release should be tagged.

For publishing binaries, we need to do the following:

* [x] Pick which set of platforms that we'll build binaries for.  This includes both operating systems (Linux, Windows, macOS) and archtectures (arm32v6 for Raspberry Pi 1/Zero, for example).
  * [x] Ensure that behavior is sane on each platform.  Windows may need changes for canonical log storage locations, for example.  This can be contributed if anyone is looking to do so.
* [x] Pick a build system.  CodeBuild is pretty reasonable and there's a [pull request](https://github.com/awslabs/amazon-ecr-credential-helper/pull/61) for it already.
* [x] Determine where binaries should be vended.
* [x] Set up an auditing system for automatically verifying the integrity of published binaries.
* [x] Build out scripts and a process for creating releases with binaries.

Some of this work is easy enough for us to accept contributions, while other work must be accomplished by the ECS/R team.

Thanks,
Sam

**Comment by lox** [comment]
I'm happy to implement the `--version` and user-agent stuff.  Seems like semver is a no-brainer and given the infrequency of change perhaps an ad-hoc release process would be a good way to start? 

Something like https://github.com/goreleaser/goreleaser would have releases done and dusted in under 60 minutes. Perhaps a build system and a verification system could be an incremental step? For a project that is infrequently updated, is it worth investing all this effort?

**Comment by singingwolfboy** [comment]
@samuelkarp Thank you very much for organizing this work. Is there a timeframe for when it might be done? It sounds like there are a few very motivated contributors who want to help, but we're all blocked on you and the ECS/R team.

**Comment by singingwolfboy** [comment]
@samuelkarp Still hoping for an answer on this.

**Comment by singingwolfboy** [comment]
@samuelkarp ping

**Comment by rpnguyen** [comment]
Hi all,

Richard from ECR here. Discussing with the team, we've decided to adopt SemVer as proposed by @lox. The first tagged release will be versioned 1.0.0.
@singingwolfboy We welcome contributions for some of these tasks. For those tasks that need to be done by the ECS/R team, we're not able to comment on specific timeframes but our team is tracking this project as part of our roadmap.

Thanks,
Richard

**Comment by singingwolfboy** [comment]
Any update on any of this work? Unfortunately, I don't have the technical knowledge to help out with this, I just want to be able to install this project from Homebrew.

**Comment by singingwolfboy** [comment]
@rpnguyen Can you please provide an update on this? This GitHub issue has been open for almost 6 months, and this problem has been present for even longer.

**Comment by estahn** [comment]
@samuelkarp @rpnguyen What's the status here? Use CircleCI/Travis and goreleaser. Seems like a no-brainer.

**Comment by estahn** [comment]
@singingwolfboy ```brew install hipages/tap/amazon-ecr-credential-helper```

* https://github.com/hipages/homebrew-tap/blob/master/Formula/amazon-ecr-credential-helper.rb
* https://github.com/estahn/amazon-ecr-credential-helper/blob/master/.goreleaser.yml

**Comment by lox** [comment]
Nice one @srizzling, I wouldn't hold your breath though!

**Comment by srizzling** [comment]
What do you mean don't hold your breath? Isn't it going to be looked at?

**Comment by lox** [comment]
Well, the bug has been open since 25 Oct 2016 (#15). The list of todo's in this issue is essentially the open-source way of saying "we aren't going to do this and don't really care about your use-case, but since you've complained so much we will make a long list of things that we are pretty sure are impossible to accomplish so that it looks like we are listening". I gave up a while back!

**Comment by estahn** [comment]
@lox got a point.
@samuelkarp Any movement on this?

**Comment by jtoberon** [comment]
@srizzling Thanks for picking this up! We are reviewing your pull request.

The purpose of separating tagged releases from publishing binaries is to unblock things like homebrew. Homebrew ought to start accepting recipes once the tagged releases work is done.

Recently, we made some changes to how we publish other related binaries. For example, see https://github.com/aws/amazon-ecs-cli/commit/459704cbffc522ca5235bd7f0ce34b0ee4b9e212 in the amazon-ecs-cli repo. We intend to follow a similar model here. We will keep you updated.

**Comment by samuelkarp** [comment]
@estahn 

> Not sure what you mean by accepting recipes. Wouldn't you just create a repository awslabs/homebrew-tap and put your formula in there?

The upstream Homebrew project maintains a set of default formulas.  They'll need tagged releases before they can accept a formula for this project; see https://github.com/Homebrew/homebrew-core/pull/18914#issuecomment-334913309.

We'll be reviewing @srizzling's pull request, which looks like it will help us get closer to being able to tag releases.

**Comment by estahn** [comment]
@samuelkarp Thanks, I see what you are referring to. I would have assumed you guys do your own homebrew tap repo.

**Comment by jtoberon** [comment]
@lox or @estahn, if you have any additional comments about @srizzling's pull request, feel free to chime in over at https://github.com/awslabs/amazon-ecr-credential-helper/pull/105.

Once this is done, and we create a tagged release, then we're happy to support pushing a recipe to the Homebrew project. It looks like there are several candidates out there, including one from @estahn and one from @singingwolfboy, and we should have consensus about which to submit. Does one of you have time to take the lead on this part?

**Comment by jtoberon** [comment]
#105 was merged. @samuelkarp @rpnguyen @deyangyin are you OK with tagging head with 1.0.0? Let's create the tag so that the homebrew formula can be created.

**Comment by srizzling** [comment]
@samuelkarp @rpnguyen @deyangyin We had REALLLY GOOD traction on this for 12 days.. whats the current status? Anything the community can help with to get this on the fast track? I want to really start using this for some production CI/CD workloads!

**Comment by deyangyin** [comment]
@srizzling We have created our tagged release with v0.1.0 which will remove obstacles for Homebrew formula. For binary release, we are working on that but Amazon has strict internal process and it will take longer for us to finish that.

**Comment by volym3ad** [comment]
I've forked and created internal binary releases here https://github.com/lun/amazon-ecr-credential-helper/releases/tag/v0.1.0-flatfy . I think you can do the same or just use mine 😉

**Comment by srizzling** [comment]
Nearly 2 months since the last update. Any progress folks?

**Comment by emmanuel** [comment]
Four months later.... crickets (and over two years(!) since the issue was raised: #15). Based on observed activity, I believe it is safe to say that Amazon has abandoned providing binary releases. That disappoints me. Ah well, life is full of disappointments.

**Comment by emmanuel** [comment]
FWIW, here's the (directly-deployable) work-around I'm using:

```
- path: /etc/systemd/system/ecr-login.service
  owner: root:root
  permissions: '0644'
  content: |
    [Unit]
    Description=Fetch Docker pull credentials for AWS ECR
    Requires=pip-install.service
    After=pip-install.service
    
    [Service]
    Type=oneshot
    # TODO: would prefer to use ecr-login from AWS, but they don't publish releases:
    #   https://github.com/awslabs/amazon-ecr-credential-helper/issues/80
    ExecStart=/bin/bash -c 'eval $$(AWS_DEFAULT_REGION="${AWS_REGION}" aws ecr get-login --no-include-email --registry-ids ${ECR_ACCOUNT_IDS})'
    
    [Install]
    WantedBy=multi-user.target

- path: /etc/systemd/system/ecr-login.timer
  owner: root:root
  permissions: '0644'
  content: |
    [Unit]
    Description=Timer for Docker pull credentials for AWS ECR
    [Timer]
    OnBootSec=0
    OnUnitActiveSec=6h
    RandomizedDelaySec=60
    [Install]
    WantedBy=timers.target
```

**Comment by estahn** [comment]
@samuelkarp How is this related to the issue? Can you shed some light on the turnaround time for the internal process to be completed?

**Comment by lox** [comment]
Does that mean you've ticked off some of the required tasks you stated in the initial issue @samuelkarp?

**Comment by samuelkarp** [comment]
@estahn We've recently started publishing the roadmap for ECS, ECR, Fargate, and EKS [here](https://github.com/aws/containers-roadmap/projects/1).

@lox To some extent, but not in a general way.  Those boxes have been ticked specifically for Amazon Linux as we're reusing the build system, publishing/hosting infrastructure, and signing/auditing mechanisms that are used for every package that is part of Amazon Linux.

**Comment by lox** [comment]
I just noticed that there are tagged releases now. Nice one @samuelkarp! 

We could probably get this into Homebrew now. @singingwolfboy any interest in re-opening https://github.com/Homebrew/homebrew-core/pull/18914?

**Comment by samuelkarp** [comment]
@lox It's in Homebrew already: https://github.com/Homebrew/homebrew-core/pull/34147

**Comment by lox** [comment]
Hell hath frozen over! 😍

**Comment by lox** [comment]
Thanks for your efforts @samuelkarp!

**Comment by estahn** [comment]
I would have thought awslabs would provide their own homebrew tap. Thus
keeping control over the install instructions and being able to integrate
the update of the tap into the release pipeline. I’m surprised you giving
this up yet can’t release a binary.

Do I still need a Golang environment with this recipe? It provides neither
a reference to a binary nor has a Golang dependency.

**Comment by lox** [comment]
@estahn: Yes, you need a golang environment for the recipe:

https://github.com/igas/homebrew-core/blob/b285f8aca6e4a1152fc08af275fdd43f6a0bcb1a/Formula/docker-credential-helper-ecr.rb#L16

**Comment by lox** [comment]
But I'd guess the bottles would contain binaries?

**Comment by willejs** [comment]
I have another workaround. Instead of waiting for statically compiled binary releases, you could download the official rpm, extract the binary and place it in the path. 

Something like this in a docker container would work:
```
RUN apk add --update rpm wget && \
    mkdir /tmp/amazon-ecr-credential-helper && \
    cd /tmp/amazon-ecr-credential-helper && \
    wget https://cdn.amazonlinux.com/blobstore/917d21e71cf32d8b418c51f477e92c60791870f0eb138423a4fa628e4671f601/amazon-ecr-credential-helper-0.2.0-2.amzn2.x86_64.rpm && \
    rpm2cpio amazon-ecr-credential-helper-0.2.0-2.amzn2.x86_64.rpm | cpio -idmv && \
    cp ./usr/bin/docker-credential-ecr-login /usr/local/bin/
```
It's not pretty, and i am not really keen on hard linking to a rpm package. It is however a trade off against building your own. Saying that, it is not the end of the world as it is vendored.

**Comment by samuelkarp** [comment]
The Amazon ECR Credential Helper has been released into the package archives for Debian Buster (testing), Debian Sid (unstable), and Ubuntu 19.04 Disco Dingo (development).  To install the credential helper in these operating systems, you can use the following commands:

```
$ sudo apt update
$ sudo apt install amazon-ecr-credential-helper
```

You will then need to configure the credential helper as described in the [README.md file](https://github.com/awslabs/amazon-ecr-credential-helper/blob/master/README.md), or in the manual page (`man docker-credential-ecr-login`).

**Comment by dschaaff** [comment]
Are there any plans to add an alpine package? I'm currently extracting the binary from the rpm as noted by @willejs above but it'd much cleaner to have a native package.

**Comment by so0k** [comment]
only official ubuntu AMIs on Amazon are Ubuntu Bionic, but there is no package for `amazon-ecr-credential-helper` today

this point may be moot as Ubuntu Disco Dingo will be officially released in a few days for now..

**Comment by willejs** [comment]
@samuelkarp can you suggest a way you would be happy to build and publish statically compiled binaries to github releases? CircleCI? I can then make a PR with the relevant config...
A lack of binaries makes this really useful utility almost impossible to use anywhere.
The published homebrew and linuxbrew defs are fine, and the debian/ubuntu images are useful, but to easily install them in any dockerfile by fetching static binaries is way easier and faster.

**Comment by samuelkarp** [comment]
Version [0.3.1](https://github.com/awslabs/amazon-ecr-credential-helper/releases/tag/v0.3.1) has been released; binary artifacts are published into S3 and linked from that page.
