### ISSUE TITLE
Windows 2016

### ISSUE THREAD

**Issue by goffinf** [awslabs/amazon-ecr-credential-helper#81]
I have been successfully using this helper on Linux (RHEL) for quite a while.

We have just started to configure AWS EC2 instances running Windows 2016 (configured for docker) and these also need to be able to pull and push images to/from ECR.

The Amazon docs for this helper here: https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/ state that it is certainly usable for Windows. We have followed the instructions for creating a Windows compatible binary.

The question that I have though is *where* should I locate the .docker/config.json file (we are using an IAM role for the AWS creds).

Most blogs, articles and such talk about ~/.docker/config.json but where would that be on my Windows 2016 instance when the CLI is invoked NOT by a user logged into the instance but via automation, such as a Jenkins job or a docker pull requested from a docker container management tool when deploying a stack ?

For Linux, we might put the .docker/config.json under the ec2-user home directory or even under /root, but where is the corresponding location for Windows ?

Regards

Fraser.

**Comment by samuelkarp** [comment]
> [W]here would that be on my Windows 2016 instance when the CLI is invoked NOT by a user logged into the instance but via automation, such as a Jenkins job

You'd put it in the `~/.docker/config.json` of the user under which automation is running.

**Comment by digitalfiz** [comment]
@goffinf Looks like its in `C:/Users/Username/.docker/machine/default/config.json` from a quick google search leading to the SO: https://stackoverflow.com/questions/37112422/docker-config-file-location-on-windows-to-e-g-enable-insecure-registry-dock

**Comment by Tim-Co** [comment]
For the system account you need to put it here: `C:\Windows\system32\config\systemprofile\.docker\config.json`

**Comment by samuelkarp** [comment]
Closing, as this question appears to be answered.
