### ISSUE TITLE
failed to make it work with assume role

### ISSUE THREAD

**Issue by loivis** [awslabs/amazon-ecr-credential-helper#84]
I've read through related issues and it seems like to work well with assume role. However I just didn't manage to get it work. I would like to post my configuration for someone to help me out.

### Goal:
I have one iam user in `master` account, with permission to assume role in another `sub` account. The role in `sub` account has managed `AdministratorAccess` policy to all resources in that account. With `assume-role`, I would like the iam user in `master` account to pull/push docker images to ecr repository in `sub` account.

### Configuration:
+ ~/.aws/credentials
```
[default]
aws_access_key_id = xxx
aws_secret_access_key = xxx
```
+ ~/.aws/config
```
[default]
output = json
region = eu-west-1
cli_history = enabled

[profile sub]
role_arn = arn:aws:iam::221234567890:role/master-access
source_profile = default
region = eu-west-1
cli_history = enabled
```

+ ~/.docker/config.json
```
{
  "credsStore": "ecr-login"
}
```

### steps
+ with `default` profile
Hepler works with ecr in current account as I've always been using.
```
bash-3.2$ echo $AWS_PROFILE $AWS_DEFAULT_PROFILE $AWS_SDK_LOAD_CONFIG

bash-3.2$ docker pull 111234567890.dkr.ecr.eu-west-1.amazonaws.com/testing:latest
latest: Pulling from testing
Digest: sha256:a09e6318d74f23fe68bad84259fedf5e6ce02c38537336419ee5e9abe10aa2af
Status: Image is up to date for 111234567890.dkr.ecr.eu-west-1.amazonaws.com/testing:latest
```

+ switch to `sub` profile as assumed role from `master` to `sub`
```
bash-3.2$ export AWS_PROFILE=sub
bash-3.2$ export AWS_SDK_LOAD_CONFIG=true
bash-3.2$ echo $AWS_PROFILE $AWS_DEFAULT_PROFILE $AWS_SDK_LOAD_CONFIG
sub true
````
assume role works as I could list images in `sub` account
```
bash-3.2$ aws ecr list-images --repository-name oracle-java
{
    "imageIds": [
        {
            "imageDigest": "sha256:a9e3c92cdc3d8f8da92bf55ca1455098e3c6447e5ce6c64b15ad59cab072a98e",
            "imageTag": "8"
        }
    ]
}
```
But error occurs while trying to run `docker pull` to the same repository.
```
bash-3.2$ docker pull 221234567890.dkr.ecr.eu-west-1.amazonaws.com/oracle-java:8
Error response from daemon: Get https://221234567890.dkr.ecr.eu-west-1.amazonaws.com/v2/oracle-java/manifests/latest: no basic auth credentials
```

+ error in `~/.ecr/logs`
```
2017-12-02T18:18:48Z [DEBUG] Could not fetch credentials for cache prefix: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2017-12-02T18:18:48Z [DEBUG] Disabling cache
2017-12-02T18:18:48Z [DEBUG] Retrieving credentials for 221234567890 in eu-west-1 (221234567890.dkr.ecr.eu-west-1.amazonaws.com)
2017-12-02T18:18:48Z [DEBUG] Calling ECR.GetAuthorizationToken for 221234567890
2017-12-02T18:18:49Z [ERROR] Error retrieving credentials: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by bmurphy1976** [comment]
Similar issue here.  We have a build server that uses assume role to deploy to multiple AWS accounts.  We cannot use this tool because it doesn't support assume role and are forced to use aws ecr get-login.  Unfortunately we've found docker login to be filled with race conditions under high contention.

**Comment by andriyfedorov** [comment]
+1

**Comment by samuelkarp** [comment]
Apologies for the delayed reply.  I was able to reproduce this, but I'm pretty sure it used to work.  I have a code change that fixes it by always enabling the shared config file, but I'd like to understand what caused it to stop respecting the `AWS_SDK_LOAD_CONFIG` environment variable.

**Comment by loivis** [comment]
@samuelkarp Thanks for your time looking into the issue. I'm a bit relieved that I'm not missing something or doing something wrong.

**Comment by samuelkarp** [comment]
`git bisect` picked 87c087b8ac42476b7825f99742c60fcd469d3895 as the first bad commit, which is of course a commit when I updated the SDK.

I think this means we need to add a bit of automated testing around assuming roles so we don't accidentally break it again.

**Comment by samuelkarp** [comment]
@loivis @bmurphy1976 @andriyfedorov I've pushed a commit that should fix this bug.  Please let me know if you still run into problems.

**Comment by loivis** [comment]
It works perfectly for me now:+1:
