### ISSUE TITLE
how to integrate with kuberenetes?

### ISSUE THREAD

**Issue by zkanda** [awslabs/amazon-ecr-credential-helper#85]
I know there's https://kubernetes.io/docs/concepts/containers/images/#using-aws-ec2-container-registry but it doesn't help if the ECR is on a completely different account. Just any hints on how to do it would appreciated.

**Comment by blau-tibco** [comment]
Your K8s AWS account probably need  be a member of "federated" accounts. That way, one or more ECR accounts in the federation can be chosen as ECR owners and grant pull/pushed access to the images that they hosted.

**Comment by samuelkarp** [comment]
I don't know if Kubernetes can use a Docker credential helper.  I think this question would be better directed to the Kubernetes project since they've built their own integration with ECR.
