### ISSUE TITLE
Problem installing package

### ISSUE THREAD

**Issue by eyalhei** [awslabs/amazon-ecr-credential-helper#86]
I have a problem installing this on my ubuntu hosted machine:
OS: ubuntu 14.04 (ec2 hosted), docker-ce installed

Steps:
```
sudo apt-get install gccgo-go
export GOPATH=<some directory>
# go get -u github.com/awslabs/amazon-ecr-credential-helper/ecr-login/cli/docker-credential-ecr-login
# github.com/aws/aws-sdk-go/aws/request
/usr/local/lib/gopath/src/github.com/aws/aws-sdk-go/aws/request/request_context_1_6.go:13:15: error: reference to undefined field or method ‘Cancel’
  r.HTTPRequest.Cancel = ctx.Done()
               ^
# github.com/cihub/seelog
/usr/local/lib/gopath/src/github.com/cihub/seelog/writers_rollingfilewriter.go:166:6: error: reference to undefined field or method ‘Reset’
    gr.Reset(f)
      ^
```

Any idea what am I doing wrong?

**Comment by samuelkarp** [comment]
@eyalhei I'm not sure what version of the Go language gccgo supports, but the credential helper requires at least Go 1.7.

If you have Docker installed, the easiest way to build the credential helper is just to run `make docker`, which will build the helper inside a Docker container using Go 1.9.

**Comment by eyalhei** [comment]
Hi @samuelkarp, thanks for the answer.
I actually found another solution for the overall question, that doesn't require me to use this, so I no longer have the environment for testing.

Thanks
