### ISSUE TITLE
Issuing retriving token

### ISSUE THREAD

**Issue by blankenshipz** [awslabs/amazon-ecr-credential-helper#88]
I've been using `ecr-credential-helper` with no probems until today. I found errors in my log stating that pull access was being denied to ECR. 

The `ecr-crednetial-helper` logs are constantly updating repeating these lines:

```
2017-12-28T22:02:32Z [DEBUG] Retrieving credentials for XXX in us-east-1 (https://XXX.dkr.ecr.us-east-1.amazonaws.com/YYY)
2017-12-28T22:02:32Z [DEBUG] Checking file cache for XXX
2017-12-28T22:02:32Z [DEBUG] Using cached token for XXX
```

Any thoughts as to what might have caused this? Pulls earlier in the afternoon seemed to work fine, the only change to ECR that I made was deleting some old tags.

**Comment by samuelkarp** [comment]
What errors are you seeing?  Have you checked the IAM policies applied to your user or role?  Have you checked the repository policy applied to your repository?

**Comment by blankenshipz** [comment]
The initial errors I saw were in nomad logs, stating that pull access had been denied for the repository. The IAM policy associated with the role looks okay to me (and hasn't changed)

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ecr:ListImages",
                "ecr:GetRepositoryPolicy",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken",
                "ecr:DescribeRepositories",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
        }
    ]
}
```

This is the policy on the repository (also unchanged):

```
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "new policy",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:DescribeRepositories",
                "ecr:GetRepositoryPolicy",
                "ecr:ListImages",
                "ecr:DeleteRepository",
                "ecr:BatchDeleteImage",
                "ecr:SetRepositoryPolicy",
                "ecr:DeleteRepositoryPolicy"
            ]
        }
    ]
}
```

I'm rebuilding the clients in my cluster currently to see if a reset fixes everything.

**Comment by samuelkarp** [comment]
Is the repository intended to be public?  Granting to `"Principal": "*"` means any AWS account would have access to the images in that repository.

**Comment by blankenshipz** [comment]
Oops! Definitely not meant to be public. Thanks for the catch! It seems like that should be updated with something like this:

```
"Principal": { "AWS": "arn:aws:iam::aws_account_id:root" }
```

I'm still baffled about why I can't seem to pull the images now when I could earlier; recreating the cluster didn't help. I also destroyed and recreated the repository. 

Here's the specific error from the nomad logs:

```
failed to initialize task "YYY" for alloc "22a88a8a-27be-6b1b-d7e3-9efcc3e814e7": Failed to pull `XXX.dkr.ecr.us-east-1.amazonaws.com/YYY:1.1.4`: API error (404): {"message":"pull access denied for XXX.dkr.ecr.us-east-1.amazonaws.com/YYY, repository does not exist or may require 'docker login'"} 
```

The `ecr-credentail-helper` log:

```
2017-12-28T23:12:00Z [DEBUG] Retrieving credentials for XXX in us-east-1 (https://XXX.dkr.ecr.us-east-1.amazonaws.com/YYY)
2017-12-28T23:12:00Z [DEBUG] Checking file cache for XXX
2017-12-28T23:12:00Z [DEBUG] Using cached token for XXX
2017-12-28T23:12:02Z [DEBUG] Retrieving credentials for XXX in us-east-1 (https://XXX.dkr.ecr.us-east-1.amazonaws.com/YYY)
2017-12-28T23:12:02Z [DEBUG] Checking file cache for XXX
2017-12-28T23:12:02Z [DEBUG] Using cached token for XXX
2017-12-28T23:12:03Z [DEBUG] Retrieving credentials for XXX in us-east-1 (https://XXX.dkr.ecr.us-east-1.amazonaws.com/YYY)
2017-12-28T23:12:03Z [DEBUG] Checking file cache for XXX
2017-12-28T23:12:03Z [DEBUG] Using cached token for XXX
```

**Comment by samuelkarp** [comment]
The default repository policy will allow access to your account, so you should be able to remove the one granting public access.

I'm not familiar with Nomad, but do you have access to the Docker daemon logs?  You may see more of a relevant error message in there.

The lines in the credential helper log seem to indicate that it's able to return an auth token successfully, so either something is corrupting the token, Nomad is not submitting the token properly, or you're getting a real AccessDenied error that is being hidden by Nomad.

**Comment by blankenshipz** [comment]
Doing a `docker pull` manually responds with:

```
Error response from daemon: Get https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/YYY/manifests/1.1.4: no basic auth credentials
```

**Comment by samuelkarp** [comment]
Have you configured the credential helper in `~/.docker/config.json`?  For reference, mine looks like this:

```json
{
	"credsStore": "ecr-login"
}
```

Can you also share a (redacted) version of what you're executing?  For example: `docker pull 123456789012.dkr.us-west-2.amazonaws.com/test:latest`.

**Comment by blankenshipz** [comment]
Here's the command I'm executing:

```
> docker pull XXX.dkr.ecr.us-east-1.amazonaws.com/YYY:1.1.4

Error response from daemon: Get https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/YYY/manifests/1.1.4: no basic auth credentials
```

The `config.json`:

```
{
  "credHelpers": {
    "XXX.dkr.ecr.us-east-1.amazonaws.com": "ecr-login"
  }
}
```

**Comment by blankenshipz** [comment]
I just found a more specific error in syslog

```
Dec 28 23:57:02 ip-10-0-1-124 dockerd[487]: time="2017-12-28T23:57:02.236510887Z" level=error msg="Not continuing with pull after error: denied: User: arn:aws:sts::XXX:assumed-role/nomad-client20171228230446599800000004/i-03543d3e416f0f883 is not authorized to perform: ecr:BatchGetImage on resource: arn:aws:ecr:us-east-1:XXX:repository/YYY"
```

double checking the iam policy associated with the instance:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ecr:ListImages",
                "ecr:GetRepositoryPolicy",
                "ecr:GetDownloadUrlForLayer",
                "ecr:GetAuthorizationToken",
                "ecr:DescribeRepositories",
                "ecr:DescribeImages",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ],
            "Resource": "*"
        }
    ]
}
```

It still looks okay to me?

**Comment by samuelkarp** [comment]
Is that the full set of policies associated with the instance? There can be multiple policies associated with a single IAM role or IAM user and the computed authorization is the union of those policies.

**Comment by blankenshipz** [comment]
There are two associated with those instances, here is the other:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeTags",
                "ec2:DescribeInstances",
                "autoscaling:DescribeAutoScalingGroups"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by blankenshipz** [comment]
@samuelkarp Is it significant at all that the `ecr-credentail-helper` log is getting updated multiple times per second? The `cache.json` seems to get updated as well - with a token. I don't know  why the token would be constantly checked/refreshed.

**Comment by blankenshipz** [comment]
nomad retries were cluttering the log... after disabling that feature a manual attempt to pull causes these entries in syslog:

```
Dec 29 14:38:27 ip-10-0-1-124 dockerd[487]: time="2017-12-29T14:38:27.632700580Z" level=info msg="Attempting next endpoint for pull after error: Get https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/YYY/manifests/latest: no basic auth credentials"
Dec 29 14:38:27 ip-10-0-1-124 dockerd[487]: time="2017-12-29T14:38:27.632745406Z" level=error msg="Handler for POST /v1.32/images/create returned error: Get https://XXX.dkr.ecr.us-east-1.amazonaws.com/v2/YYY/manifests/latest: no basic auth credentials"
```

**Comment by blankenshipz** [comment]
I'm still working through the solution here but it seems the problem isn't related to `ecr-credentail-helper`.

I found an error that said the `docker-credentail-ecr-login` executable was not found on $PATH - it seems that my version was renamed to `docker-credential-ecr`. 

The way these helper scripts are accessed by the daemon is by pre-pending the provided name with `docker-credentail-`; I had `ecr-login` in the `credHelpers` section of `~/.docker/config.json`  which is why my manual pulls weren't working however in my nomad configuration I'm specifying `ecr`. I think this is due in part to [this bit of somewhat confusing documentation](https://www.nomadproject.io/docs/drivers/docker.html#authentication)

I'm not sure how this ever worked. Haven't quite fixed it yet. 

@samuelkarp thanks for your help with this!
