### ISSUE TITLE
Can't use ECR helper alongside GHCR login

### ISSUE THREAD

**Issue by siferati** [awslabs/amazon-ecr-credential-helper#908]
## Description

The README states it's possible to use ECR Docker Credential Helper alongside existing docker login authentication tokens.
But this doesn't seem to work for GitHub Container Registry?

How can I simultaneously login to GHCR and ECR??

#### ECR + GHCR

```json
{
    "credsStore": "ecr-login",
    "auths": {
        "ghcr.io": {
            "auth": "MY_TOKEN"
        }
    }
}
```

- `docker pull <ghcr>` **fails** (`Error response from daemon: Head "...": unauthorized`)
- `docker pull <ecr>` succeeds

---

I can pull images separately from both GHCR and ECR, so it's not an issue with my credentials.
Only when trying to login to both registries as above do I fail to pull from GHCR.

#### Only GHCR

```json
{
    "auths": {
        "ghcr.io": {
            "auth": "MY_TOKEN"
        }
    }
}
```

- `docker pull <ghcr>` succeeds
- `docker pull <ecr>` fails (expected since no ecr login)

#### Only ECR

```json
{
    "credsStore": "ecr-login"
}
```

- `docker pull <ghcr>` fails (expected since no ghcr login)
- `docker pull <ecr>` succeeds

**Comment by swagatbora90** [comment]
Hi @siferati, this may be a issue with how docker handles `credStore`.

Have you tried using [credHelpers](https://docs.docker.com/reference/cli/docker/login/#credential-helpers) instead?
```
{
        "credHelpers": {
                "public.ecr.aws": "ecr-login",
                "<account-id>.dkr.ecr.<region>.amazonaws.com": "ecr-login"
        },
        "auths": {
                "ghcr.io": {
                        "auth": "<token>"
                 }
          }
}
 ```

**Comment by siferati** [comment]
@swagatbora90 Thanks, that solved the issue!

So is the README outdated and this section no longer applies to recent docker versions?
https://github.com/awslabs/amazon-ecr-credential-helper/blob/69e8c24e6fc115fd00d7c363cde156570ce73144/README.md?plain=1#L223-L237

**Comment by swagatbora90** [comment]
Yes, I think the README needs to be updated, since I was not able to make this work as well. 

I also found this old [issue](https://github.com/moby/moby/issues/30880) where a lot of folks reported issues with using `credStore` and `auth` tokens.  I ran my test of docker 25.0.6 btw.

**Comment by swagatbora90** [comment]
Documentation has been updated to reflect the above behavior.
