### ISSUE TITLE
Helper not working with "service create" on swarm

### ISSUE THREAD

**Issue by nvivo** [awslabs/amazon-ecr-credential-helper#91]
I setup the helper in a server, and it works fine when I call docker pull manually with a regular user. I set the config also on /root/.aws and /root/.docker so the root user has the same config as the regular user.

But when I run `docker service create` in a root node, it fails with `no basic auth` on the worker node.

How do I set this up so it works with all users?

**Comment by igorpdasilvaa** [comment]
Hi, @nvivo  yo fixed it ? i know we can use --with-registry-auth to create or update the service but when inside a cluster with multiple nodes this doesn't work fine, the container of service is created in a node, but if this node become offline the swarm can't up this again giving `no such image`  error
