### ISSUE TITLE
Unknown options: --no-include-email

### ISSUE THREAD

**Issue by dulimitta** [awslabs/amazon-ecr-credential-helper#92]
aws --version shows as below.
aws-cli/1.14.25 Python/2.7.12 Linux/4.4.0-1048-aws botocore/1.8.29

I guess I am on latest aws-cli. But still I am getting "Unknown options: --no-include-email" error when I login into ECS from Jenkins. Surprisingly the error doesn't show up when I try ECS login manually.

**Comment by samuelkarp** [comment]
@dulimitta The best place to ask questions about the AWS CLI is [the AWS CLI GitHub repository](https://github.com/aws/aws-cli/).  This repository is not related to to the AWS CLI or the error you're seeing.

**Comment by dulimitta** [comment]
Sure @samuelkarp Thank you.
