### ISSUE TITLE
Provide support for proxies

### ISSUE THREAD

**Issue by TDeprez** [awslabs/amazon-ecr-credential-helper#99]
This helper fails when ran behind a proxy. Could you provide an option to configure a proxy please?

Logs from ~/.ecr/log/
2018-02-08T11:22:51Z [DEBUG] Retrieving credentials for 8xxxx5 in eu-west-1 (8xxxx5.dkr.ecr.eu-west-1.amazonaws.com)
2018-02-08T11:22:51Z [DEBUG] Checking file cache for 8xxxx5
2018-02-08T11:22:51Z [DEBUG] Calling ECR.GetAuthorizationToken for 8xxxx5
2018-02-08T11:22:51Z [ERROR] Error retrieving credentials: RequestError: send request failed
caused by: Post https://ecr.eu-west-1.amazonaws.com/: read tcp 1xxxx2:38927->54.239.33.135:443: read: connection reset by peer

This works if the https_proxy is set in my local environment and ran manually, but that won't be the case when kubernetes is trying to pull an image.

Docker proxy has already been set and can pull images from docker hub without issue.

**Comment by grezar** [comment]
@TDeprez I also have the same problem. Do you solve this problem?

**Comment by TDeprez** [comment]
@grezar I was running it in a container so was able to add in the proxy settings. However as I was using Kubernetes I then found this wasn't the best way of doing things and ended up just using the 'aws ecr get-login' command and parsing the result.

**Comment by samuelkarp** [comment]
In general you can use the `HTTP_PROXY` environment variable to control the proxy settings.  I am not familiar with how Kubernetes invokes Docker, though my understanding is that the Kubernetes AWS cloud provider handles authenticating with Amazon ECR.
